ceph/ceph-qa-suite

tasks/mds_flush.py
Now that #10387 is fixed in master, we can tighten
up this test to ensure that the expected deletions
are happening.
=> tasks/mds_flush: remove #10387 workaround

tasks/qemu.py
This resolves these two tracker issues:
http://tracker.ceph.com/issues/10275
http://tracker.ceph.com/issues/10276
Even though we are now using qemu-kvm, the version that is install wasn't compiled with rbd support so qemu tests will still fail when starting up qemu.  I've cut another ticket (http://tracker.ceph.com/issues/10480) to fix this as it can't be done in ceph-qa-suite.
=> Use qemu-kvm in the qemu task for rpm based systems.

tasks/cephfs/filesystem.py, tasks/cephfs/mount.py, tasks/mds_journal_repair.py
This tests the new #9883 repair functionality
where we selectively scrape dentries out of
the journal while the MDS is offline.
=> tasks/mds_journal_repair: create new test

suites/fs/basic/tasks/cfuse_workunit_misc.yaml, suites/fs/basic/tasks/cfuse_workunit_quota.yaml
Quota script is moved out of fs/misc so that kclient
doesn't try to run it.  Update cfuse suite to find
the new location, and only enable quota for this
one script rather than enabling across
all misc tests.
Fixes: #10579
=> suites/fs: isolate quota task

suites/fs/basic/tasks/cephfs_scrub_tests.yaml, tasks/mds_scrub_checks.py
Change the config option from mds_id to mds_rank to reflect the
fact that it's the rank we want to make use of (and will continue
to want when we're doing stuff like force exporting from one rank
to another).
Fixes: #10361
=> mds_scrub_checks: only direct ops at the active MDS

suites/fs/basic/tasks/cfuse_workunit_suites_tiobench.yaml, suites/fs/samba/workload/cifs-tiobench.yaml, suites/fs/traceless/tasks/cfuse_workunit_suites_tiobench.yaml, suites/kcephfs/cephfs/tasks/kclient_workunit_suites_tiobench.yaml, suites/krbd/rbd/tasks/rbd_workunit_suites_tiobench.yaml, suites/rbd/librbd/workloads/qemu_tiobench.yaml, suites/upgrade-fs/fs/5-next-workload/tiobench.yaml
The tiobench software has been abandoned upstream for years. Fedora and
Debian are no longer shipping the tiobench package, so we've had to
carry the package ourselves in the Ceph project, and we're trying to
slim down our dependencies where it makes sense to do so.
Nuke the tiobench tests.
http://tracker.ceph.com/issues/10152 Refs: #10152
Signed-off-by: Ken Dreyer <kdreyer@redhat.com>
(cherry picked from commit 8a317125fc542667e57c66017db6e80a3edc24f2)
=> drop tiobench tests

suites/rbd/singleton/all/formatted-output.yaml
Instead of fetching it from the tip of the master branch.
=> rbd: get src/test/cli-integration/rbd/formatted-output.t from giant

suites/teuthology/ceph/clusters/single.yaml, suites/teuthology/ceph/distros/rhel.yaml, suites/teuthology/ceph/distros/ubuntu.yaml, suites/teuthology/ceph/tasks/teuthology.yaml, suites/teuthology/no-ceph/clusters/single.yaml, suites/teuthology/no-ceph/distros/baremetal.yaml, suites/teuthology/no-ceph/distros/rhel7.0.yaml, suites/teuthology/no-ceph/distros/ubuntu14.04.yaml, suites/teuthology/no-ceph/distros/vps.yaml, suites/teuthology/no-ceph/distros/vps_rhel7.0.yaml, suites/teuthology/no-ceph/distros/vps_ubuntu14.04.yaml, suites/teuthology/no-ceph/tasks/teuthology.yaml
This suite locks machines of varying distros and runs the 'tests' tasks
against them. This will test both vps locking / provisioning and
baremetal locking.
Also, we test the chef and install tasks with ubuntu and rhel.
=> Created a new suite to test teuthology

tasks/workunit.py
@jdurgin Pls take a look and then I will send it to Zack
=> Fixes #10869, added {role} to the dir name that stores the workunits.list

suites/teuthology/no-ceph/distros/ubuntu12.04.yaml, suites/teuthology/no-ceph/distros/vps_centos6.5.yaml, suites/teuthology/no-ceph/distros/vps_debian7.yaml, suites/teuthology/no-ceph/distros/vps_rhel6.4.yaml, suites/teuthology/no-ceph/distros/vps_rhel6.5.yaml
I decided not to symlink because I'm using a file name convention to
easily filter out distros that need a vps.
=> Mirror the supported distros used in nightlies in the teuthology suite

suites/powercycle/osd/tasks/admin_socket_objecter_requests.yaml, suites/rados/thrash/workloads/admin_socket_objecter_requests.yaml, tasks/restart.py, tasks/workunit.py
This probably redirects to http://ceph.com but ceph.newdream.net still appears in some places
http://tracker.ceph.com/issues/9922 Fixes: #9922
Signed-off-by: Armando Segnini  <armando.segnini@telecom-bretagne.eu>
=> teuthology: some suites still use http://ceph.newdream.net

suites/hadoop/basic/tasks/repl.yaml, suites/hadoop/basic/tasks/terasort.yaml
Fixes internal-tests, and adds terasort. Depends on hadoop-workunit PR in ceph repo.
=> Hadoop workunits

tasks/workunit.py
Fixes: #10600
Backport: hammer, giant, firefly, dumpling
=> workunit: include /usr/sbin in the PATH for all commands

tasks/ceph.py
Specifically, I want to know *who* is running the ceph-osd that is holding
the files open.
=> ceph: ps axf too before lsof

tasks/qemu.py, tasks/userdata_setup.yaml
RHEL 7.0 doesn't have virtio-9p, so we switched to using an nfs mount so that the guest can share files with the host during the qemu tasks.  This will work across all distros.
Tested in octo for both rhel and ubuntu.
http://pulpito.ceph.redhat.com/qemu-rhel-issue-10680/
http://pulpito.ceph.redhat.com/qemu-ubuntu-issue-10680/
=> Use an NFS mount instead of virtio-9p in the qemu task

tasks/ceph_manager.py
* add a wrapper to log uncaught exception to self.logger, greenlet also
prints the backtrace and exception to stderr, but teuthology.log does
not capture stderr. so we need to catch them by ourselves to reveal
more info to root-cause this issue.
* log uncaught exception thrown by Thrasher.do_thrash() to self.log.
See: #10630
=> Thrasher: log backtrace of thrown exception

tasks/apache.conf.template
3db4d6f93ba3e58b652c3dadefe5c545bd94a2a3 was incorrectly cherry picked
in 563eb8ce1b7c04948908998d8421e1fedebd403f and misses the removal of
{apache24_modconfig}. As a consequence, the MPM module is loaded
twice:
apache2: Configuration error: More than one MPM loaded.
http://tracker.ceph.com/issues/10801 Fixes: #10801
=> apache: change template to load mpm worker module (part 2)

.gitignore, tasks/calamari_setup.py, tasks/ceph_deploy.py, tasks/ceph_fuse.py, tasks/ceph_manager.py, tasks/cephfs/mount.py, tasks/divergent_priors.py, tasks/osd_failsafe_enospc.py, tasks/peering_speed_test.py, tasks/populate_rbd_pool.py, tasks/repair_test.py, tox.ini
This PR adds a `tox.ini` and fixes all the `F` class errors that are usually the worst (most of them will cause code to break).
Issue link: http://tracker.ceph.com/issues/10954
Output examples for before/after
Before:
tox -r
flake8 create: /Users/alfredo/python/upstream/ceph-qa-suite/.tox/flake8
flake8 installdeps: flake8
flake8 runtests: PYTHONHASHSEED='2738397779'
flake8 runtests: commands[0] | flake8 --select=F
./tasks/ceph_fuse.py:9:1: F401 'run' imported but unused
./tasks/calamari_setup.py:7:1: F401 're' imported but unused
./tasks/divergent_priors.py:7:1: F401 'ceph_manager' imported but unused
./tasks/divergent_priors.py:8:1: F401 'teuthology' imported but unused
./tasks/divergent_priors.py:59:20: F821 undefined name 'mon'
./tasks/divergent_priors.py:71:14: F821 undefined name …
=> impelement a tox job to catch bad linter errors

tasks/qemu.py, tasks/userdata_setup.yaml
(cherry picked from commit 93f2bea3530a523c7b2ac0575033697cea893f2d)
=> DNM: Use an NFS mount instead of virtio-9p in the qemu task

suites/rbd/singleton/all/formatted-output.yaml
The hb=firelfy cannot end the URL because of this constraint.
=> all tests must end with .t

tasks/lost_unfound.py
Fixes http://tracker.ceph.com/issues/11013
=> Fixes #11013, use time.sleep instead of manager.sleep which isn't there.

suites/rados/thrash/workloads/ec-radosbench.yaml
If a shard is missing during a radosbench it can safely be
ignored. It will either be recovered and radosbench will complete
successfully. Or there are too many shard missing to recover the object
and radosbench will fail. Either way we can rely on radosbench to
accurately report success or failure.
=> whitelist shard missing errors

tasks/radosgw_admin.py
Signed-off-by: Alfredo Deza <adeza@redhat.com>
(cherry picked from commit 9b6ff638735d03c1f3304198fad51ca701a2c8bd)
Conflicts:
tasks/radosgw_admin.py
the context changed but the patch seems otherwise good
=> create a new get_acl helper to ensure proper xml is compared

suites/fs/basic/tasks/cfuse_workunit_suites_truncate_delay.yaml
We need to change into the directory during the same shell session as we actually
run the dd...
Fixes: #10861
Backport: hammer, giant, firefly
=> fs: fix up dd testing again

tasks/radosgw_admin.py, tasks/radosgw_admin_rest.py, tasks/util/rgw.py
Move the get_user_summary(out, user) logic to util.rgw so that it can be
shared between radosgw_admin_rest.py and radosgw_admin.py and modify
them accordingly.
http://tracker.ceph.com/issues/11180 Fixes: #11180
(cherry picked from commit 97e6d808f086834f2350084d5de36be285ad2bde)
Conflicts:
tasks/radosgw_admin.py
=> ensure summary is looked for the user we need (part 2)

erasure-code/ec-rados-default.yaml, erasure-code/ec-rados-sequential.yaml, suites/upgrade/giant-x/parallel/2-workload/sequential_run/ec-rados-default.yaml, suites/upgrade/giant-x/parallel/2-workload/sequential_run/ec-rados-sequential.yaml
The ec-rados-default.yaml started with:
workload:
sequential:
which is only suitable for suites/upgrade/giant-x/parallel/2-workload/sequential_run/ec-rados-default.yaml
because suites/upgrade/giant-x/parallel/1-giant-install/giant.yaml has
- parallel:
- workload
- upgrade-sequence
The same file was included in contexts where the parallel task was not
used and the workload did not run:
./suites/upgrade/firefly-x/stress-split-erasure-code/5-workload/ec-rados-default.yaml
./suites/upgrade/giant-x/stress-split-erasure-code/5-workload/ec-rados-default.yaml
./suites/upgrade/giant-x/stress-split-erasure-code-x86_64/5-workload/ec-rados-default.yaml
The ec-rados-default.yaml is modified to be a task instead of a
sequential task in a parallel tasks. The ec-rados-sequential.yaml is
added and is …
=> erasure-code: enable ec-rados-default.yaml

tasks/calamari_setup.py
- fix ISO mounting for older distros
- drop the "build the image" code
- simplify configuration: "test_image" points to the path or URL for the image to test
- require that test_image be set
- add a clearer config defaults mechanism
=> calamari_setup fixes

tasks/samba.py
man samba(8) contains sentences:
To shut down a user's smbd process it is recommended that SIGKILL (-9)
NOT be used, except as a last resort, as this may leave the shared
memory area in an inconsistent state. The safe way to terminate an smbd
is to send it a SIGTERM (-15) signal and wait for it to die on its own.
=> task/samba: use SIGTERM to stop samba server

tasks/mds_journal_repair.py
DNM: don't merge this until https://github.com/ceph/ceph/pull/4282, it's just an update to keep up with that change.
Tests inspecting snapserver dump need updating
to reflect the rename.
=> DNM: tasks: s/pending_create/pending_update/ in MDS

tasks/samba.py
if mount point is not used by anyone, both fuser and losf return 1
Fixes: #10624
=> task/samba: ignore return code of fuser/losf

tasks/ceph.py, tasks/ceph_deploy.py, tasks/cephfs/filesystem.py, tasks/mds_journal_repair.py
This isn't a nice "cherry-pick -x" backport because master version of this is waiting for https://github.com/ceph/ceph-qa-suite/pull/383
=> hammer: fix ceph-deploy task with CephFS (#11316)

tasks/samba.py
if mount point is not used by anyone, both fuser and losf return 1
Fixes: #10624
(cherry picked from commit c049387b7b0832e78a4a1370691798f726985799)
=> [hammer backport] task/samba: ignore return code of fuser/losf

suites/fs/recovery/tasks/journal-repair.yaml
"bad backtrace on dir ino" is emitted because
journaltool's recover-dentries doesn't write
backtraces.
=> suites: log whitelist for journal repair test

suites/fs/recovery/tasks/pool-perm.yaml, tasks/cephfs/test_pool_perm.py
This tests that client checks pool permission before
copy data to its cache.
=> tasks/cephfs: add test_pool_perm

suites/rados/singleton-nomsgr/all/11429.yaml, tasks/ceph_manager.py, tasks/radosbench.py, tasks/utility.py
This patch also adds some convenience facilities for making
some of the ceph_manager methods into tasks usable from a
yaml file.
=> suites/rados: add test for 11429

suites/fs/recovery/tasks/journal-repair.yaml
This is the table unreadable error for mds1_inotable that
we get when trying to start an MDS whose objects are gone.
=> suites/fs: add another log whitelist to journal-repair

tasks/cephfs/fuse_mount.py
=> tasks/cephfs: mount fusectl before listing fuse connections

tasks/cephfs/cephfs_test_case.py
...to avoid OSDMap modifications happening in the
background due to blacklist expiry.
Fixes: #11301
=> tasks/cephfs: reset osd blacklist between tests

tasks/cephfs/cephfs_test_case.py
=> tasks/cephfs: fix typo in blacklist clearing

tasks/cephfs/test_client_recovery.py
To test that metadata written recently is
preserved across a client+server crash when
barriered with a directory fsync.
=> tasks/cephfs: add TestClientRecovery.test_fsync

clusters/fixed-2-ucephfs.yaml, suites/fs/basic/clusters/fixed-2-ucephfs.yaml, suites/fs/basic/clusters/fixed-3-cephfs.yaml, suites/fs/snaps/clusters/fixed-2-ucephfs.yaml, suites/fs/snaps/clusters/fixed-3-cephfs.yaml, suites/fs/standbyreplay/clusters/standby-replay.yaml, suites/fs/thrash/clusters/mds-1active-1standby.yaml, suites/fs/traceless/clusters/fixed-2-ucephfs.yaml, suites/fs/traceless/clusters/fixed-3-cephfs.yaml, suites/fs/verify/clusters/fixed-2-ucephfs.yaml, suites/fs/verify/clusters/fixed-3-cephfs.yaml, suites/multimds/libcephfs/clusters/3-mds.yaml, suites/multimds/libcephfs/clusters/9-mds.yaml, suites/multimds/verify/clusters/3-mds.yaml, suites/multimds/verify/clusters/9-mds.yaml
This reconfigures the cluster yaml fragments for most of the filesystem-related tests to reduce the number of nodes they use.
=> Reduce fs test node usage

tasks/ceph_manager.py
Signed-off-by: Alfredo Deza <adeza@redhat.com>
(cherry picked from commit f7c1ca4a1e23b03ecf86d5e67d563f95b3a82f99)
Conflicts:
tasks/ceph_manager.py
lines shifted but nothing significant changed
=> add the log object to ceph_manager

suites/smoke/1node/clusters/fixed-1.yaml, suites/smoke/1node/tasks/ceph-deploy.yaml, tasks/ceph_deploy.py
Single Node Ceph-deploy tests to exercise commonly used CLI and test basic init startup
- Need to add 1 node yaml for this test in smoke suite
=> Single node ceph-deploy tests to exercise commonly used cli

tasks/cephfs/test_auto_repair.py
When client capabilities get released, MDS may update corresponding
inodes' client writable range and mark those inodes dirty. The auto
repair test expects MDS to trim inodes from its cache, but MDS can't
trim dirty inodes. So we should flush journal after umount.
Fixes: #12172
(cherry picked from commit 835ad8b8f3038290846c612b66f3bffcc5755338)
=> cephfs/test_auto_repair.py: flush journal after umount

tasks/rgw.py
This fixes a bug where we were setting up mod_fastcgi to use both tcp
and uds.
=> rgw: do not enable both tcp and uds for fastcgi

overrides/3-size-2-min-size.yaml
Workaround for 12231.
Fixes: #12231
=> 3-size-2-min-size: keep 4 in during thrashing

suites/fs/basic/dirfrag/frag_enable.yaml, suites/fs/multiclient/dirfrag/frag_enable.yaml, suites/fs/recovery/dirfrag/frag_enable.yaml, suites/fs/snaps/dirfrag/frag_enable.yaml, suites/fs/standbyreplay/dirfrag/frag_enable.yaml, suites/fs/thrash/dirfrag/frag_enable.yaml, suites/fs/traceless/dirfrag/frag_enable.yaml, suites/fs/verify/dirfrag/frag_enable.yaml
Setting this in tests globally as a precursor
to enabling it by default in the shipping code.
Set a low mds bal split size in order to make
us hit the fragmentation code more often in
than we usually would in a single MDS environment.
=> suites/fs: enable directory fragmentation

suites/upgrade/hammer/newer/2-workload/s3tests.yaml
Per IRC chat by Yehuda, Josh and Dan:
"the purpose of firefly-original in general was for upgrades from prior point releases of firefly, where newer tests on the firefly branch would fail
it shouldn't be used if it's just a firefly->hammer upgrade though, the plain old firefly branch should be fine for that"
=> Changed s3tests ref to firefly

suites/upgrade/dumpling-firefly-x/parallel/0-cluster/start.yaml
added "mon debug unsafe allow tier with nonempty snaps: true"
@athanatos I missed this on this suite FYI
=> Fixes #12021 for upgrade/dumpling-firefly-x suite

machine_types/vps.yaml, tasks/ceph_fuse.py, tasks/cephfs/fuse_mount.py
1) add a wait time before the mount attempt to let the cluster get set up.
By default this should be skipped, but for VMs and known-slow systems we
can give them 60 seconds.
2) Make the timeout configurable, with a 30-second default, but override it
for VM tests.
http://tracker.ceph.com/issues/12320 Fixes: #12320
=> tasks/ceph_fuse.py: virtual machines need flexible mount timeout

tasks/calamari_setup.py
Otherwise, ceph-deploy will install an apt source that points to
ceph.com, which will override the local ISO repos.
Also, fix a cut'n'paste bug (the second set of installs needs to be
--osd).  This was harmless, as the ceph-deploy currently installs
everything, but would have broken the once package splits happen.
=> calamari_setup: Add --no-adjust-repos to ceph-deploy install --<type>

tasks/ceph_manager.py
At the default interval this generates tons of log noise.
=> tasks/ceph_manager: be silent about sending SIGHUPs

tasks/ceph.py
=> tasks: fix syntax error in ceph.py

tasks/multibench.py, tox.ini
It wasn't configured to error before, should prevent issues like this: https://github.com/ceph/ceph-qa-suite/pull/521
=> Include `SyntaxError` checks in linter

erasure-code/ec-rados-plugin=lrc-k=4-m=2-l=3.yaml, suites/rados/thrash-erasure-code-big/cluster/12-osds.yaml, suites/rados/thrash-erasure-code-big/fs, suites/rados/thrash-erasure-code-big/msgr-failures, suites/rados/thrash-erasure-code-big/thrashers/default.yaml, suites/rados/thrash-erasure-code-big/thrashers/mapgap.yaml, suites/rados/thrash-erasure-code-big/thrashers/morepggrow.yaml, suites/rados/thrash-erasure-code-big/thrashers/pggrow.yaml, suites/rados/thrash-erasure-code-big/workloads/ec-rados-plugin=lrc-k=4-m=2-l=3.yaml
Add a workload that uses the lrc erasure code plugin. Instead of adding
it to suites/rados/thrash-erasure-code/workloads, a new suite is created
at suites/rados/thrash-erasure-code-big because it needs more OSDs than
other erasure code plugins. The alternative would be to increase the
number of OSDs for all erasure code plugins, but that would needlessly
increase the resources requirements.
* cluster/12-osds.yaml creates a 12 OSDs, 3 MONs cluster
* thrash-erasure-code-big/thrashers/*.yaml are the same as
thrash-erasure-code/thrashers/*.yaml except they require that at
least 8 OSDs are in at all times (instead of 4) because lrc PGs with
k=4, m=2, l=3 are undersized if they do not have 8 OSDs. It is
possible that crush fails to map 8 OSDs when only 8 OSDs are
available, but that must not …
=> erasure-code: lrc plugin workload

tasks/calamari_setup.py
In RHCS 1.2 we don't have a `/mnt/MON` directory. The intention of 35c6363a1eaf5011e26be8561ffcd4e9324d13a2 was to handle this condition, but in 1.2, the non-zero return code makes Teuthology fail the whole test.
We don't want *Teuthology* itself to act on the return code here; we simply want to know what it was and structure the rest of the test accordingly.
=> calamari_setup: handle RHCS 1.2 (missing /mnt/MON)

tasks/calamari_setup.py
In our RHCS 1.3 ceph-deploy docs, we tell users to run "ceph-deploy install --cli" on their calamari admin node, but our smoke test wasn't actually doing this.
See https://bugzilla.redhat.com/1252929 , "[Ubuntu 1.3.0] - ceph-deploy install --no-adjust-repos --cli `hostname` is failing with a Traceback error"
=> calamari_setup: install "cli" utils on Calamari node

tasks/ceph_deploy.py
-- Use branch from config for ceph-deploy testing, (wip-*, master, next etc), since packages are available for all distro's
=>  - Use branch from config for ceph-deploy testing

distros/supported/centos_6.5.yaml, distros/supported/centos_7.0.yaml, distros/supported/ubuntu_12.04.yaml
CentOS 6 and Ubuntu 12.04 are not support after Infernalis.
CentOS 7 is supported starting with Infernalis.
=> update the list of supported distributions

tasks/ceph_deploy.py
Fixes: http://tracker.ceph.com/issues/12758
=> ceph_deploy: if a branch is given, use it when installing rgw

tasks/cephfs/test_client_recovery.py
So that we can get a failure instead of a hang in
=> tasks/cephfs: timeout on wait in test_network_death

tasks/cephfs/fuse_mount.py
Previously were defaulting to a string, which
always compared greater than elapsed, so never
timed out.
Fixes: #12820
=> tasks/cephfs: fix mount_timeout config loading

tasks/qemu.py
try deleting leftover entries for previous job
Fixes: #12806
=> tasks/qemu: avoid adding duplicated entries to /etc/exports

suites/upgrade/hammer/older/0-cluster/start.yaml, suites/upgrade/hammer/older/2-workload/rbd.yaml, suites/upgrade/hammer/older/3-upgrade-sequence/upgrade-mon-osd-mds.yaml, suites/upgrade/hammer/older/3-upgrade-sequence/upgrade-osd-mon-mds.yaml
Between the Giant and Hammer releases, the symbols exported from librados/librbd
were cleaned up.  This creates a short window of time between installing
upgraded packages where symbol lookup errors could occur.
Fixes: #12563
=> suites/hammer/older: do not upgrade client while running RBD import/export

suites/rados/singleton-nomsgr/all/cache-fs-trunc.yaml
This is meant to exercise the code for https://github.com/ceph/ceph/pull/5442
Checked against hammer to ensure it [fails] \(test passes on [wip-12551]\). The osd logs for failed/passed jobs show little differences between them (in terms of osd ops); truncate `seq` and `size` are similar on both outputs but given that the changes in the PR do get exercised, I believe the patch is what makes the difference (although I could be wrong).
The test passes on hammer if we wait for the client to finish the (actual) async `truncate` by including a `sleep` between the truncate and the flush/eviction (e.g. `sleep 10`). The actual error message is:
```
2015-08-26 00:34:17.553532 7fdd159eb700  1 -- 10.214.133.22:6804/23913 --> 10.214.133.22:0/1025141 -- osd_op_reply(3 10000000000.00000016 [cache-evict] …
```
=> Adds test for ceph/pull/5442

suites/rados/singleton-nomsgr/all/11429.yaml, suites/rados/upgrade/hammer-x-singleton/3-thrash/default.yaml
=> rados: 'failed to encode ...' warnings are normal on upgrades

suites/teuthology/buildpackages/buildpackages.yaml, suites/teuthology/buildpackages/ubuntu_14.04.yaml, tasks/buildpackages.py, tasks/buildpackages/Makefile, tasks/buildpackages/make-debs.sh
Build Ceph packages from source for the required revision, os_type,
os_version and architecture and upload them to the gitbuilder
repository.
http://tracker.ceph.com/issues/13031 Fixes: #13031
=> buildpackages: build ceph packages and upload them

tasks/ceph.py
Ceph PR https://github.com/ceph/ceph/pull/5416 was causing tests to occasionally fail because it took some time for the MDSes to actually be ready to go. Wait for them to be happy during initial setup.
We set a 300 second timeout just to make sure we don't eat up machines for forever.
=> ceph: wait for CephFS to be healthy before proceeding

tasks/s3tests.py
Use old branches as is without 'ceph-' for firefly, hammer etc
=> Use old branches as is without 'ceph-' for firefly, hammer etc

distros/a-supported-distro.yaml, distros/supported/a-supported-distro.yaml, suites/upgrade/hammer-x/v0-94-4-stop/a-supported-distro.yaml
The a-supported-distro.yaml file must be outside of the supported distro
directory otherwise it will have all suites including the distro
directory run CentOS 7 jobs twice.
=> do not duplicate CentOS 7 runs

tasks/cephfs/fuse_mount.py
For cases where we have e.g. poked the fuse abort
file for a process, but it's still not dying.  Because
this is a special class of error (unlike e.g. when
we force umount something because the network is gone)
raise the error instead of trying again to kill
the client.
Fixes: #11835
=> tasks/cephfs: time out on ceph-fuses that don't die

tasks/buildpackages.py, tasks/buildpackages/Makefile, tasks/buildpackages/common.sh, tasks/buildpackages/make-deb.sh, tasks/buildpackages/make-rpm.sh
Instead of relying on git_base_url, use the get_ceph_git_url() to obtain
the URL of the Ceph repository to use with git clone. This allows the
user to override it via the git_ceph_url configuration option and the
--git-ceph-url command line option to teuthology-openstack.
http://tracker.ceph.com/issues/11883 Refs: #11883
=> buildpackages: get Ceph git url via get_ceph_git_url()

tasks/buildpackages/Makefile, tasks/buildpackages/centos-6.5-user-data.txt, tasks/buildpackages/centos-7.0-user-data.txt, tasks/buildpackages/ubuntu-14.04-user-data.txt, tasks/buildpackages/user-data.txt
CentOS 6.5 needs to install a package and reboot to grow the root file
system. Instead of assuming a common user-data.txt file can fit all
Operating Systems, make one user data per os-type/os-version combination.
=> buildpackages: user-data must be per os-type/os-version

tasks/buildpackages.py
The process run by flock must not inherit the file descriptor because
this will cause the lock to be held forever should the command survive
the call to flock. This is for instance the case for the ssh-agent.
=> buildpackages: flock must --close

tasks/ceph_deploy.py
The config paramter of download_ceph_deploy does not have a ceph-deploy
item, therefore the ceph-deploy-branch parameter is always assumed to be
master.
=> ceph-deploy: fix ceph-deploy-branch config options

suites/powercycle/osd/tasks/rados_api_tests.yaml, suites/rados/monthrash/workloads/rados_api_tests.yaml, suites/rados/thrash/workloads/rados_api_tests.yaml, suites/rados/verify/tasks/rados_api_tests.yaml, suites/smoke/basic/tasks/mon_thrash.yaml, suites/smoke/basic/tasks/rados_api_tests.yaml, suites/upgrade/firefly-hammer-x/parallel/5-workload/rados_api.yaml, suites/upgrade/hammer-x/parallel/5-final-workload/rados_mon_thrash.yaml, suites/upgrade/hammer-x/point-to-point-x/point-to-point.yaml, suites/upgrade/hammer/point-to-point/point-to-point.yaml
A new test verifies that we are stopped by the pool quota (and get
the right error messages or block).  See ceph.git
32962740ce9211626d310a002b23afeb0d05b500.
=> log-whitelist 'reached quota' for librados test.sh

suites/upgrade/hammer-x/point-to-point-x/point-to-point.yaml
Can't do 2 rgw's on the same client id.
=> upgrade/hammer-x/point-to-point: use different client for second rgw

suites/krbd/rbd/tasks/rbd_fio.yaml, suites/krbd/thrash/workloads/rbd_fio.yaml, suites/rbd/librbd/workloads/rbd_fio.yaml, tasks/rbd_fio.py
This test can be used to exercise all rbd supported formats/features and can be used along with thrash/powercuts,  Can be used with large disks and simulate VM installation test cases. I am still testing this with other thrash tests for complete results.
=> Add rbd fio test to exercise block IO on all format/features

debug/buildpackages.yaml, suites/teuthology/buildpackages/tasks/builpackages.yaml
When using the teuthology-openstack command, buildpackages is implicit
and does not need to be included when running the test suite. Move the
stanza to the debug directory as a reminder when debuging.
=> buildpackages: implicit for OpenStack

suites/teuthology/buildpackages/tasks/branch.yaml, suites/teuthology/buildpackages/tasks/builpackages.yaml, suites/teuthology/buildpackages/tasks/default.yaml, suites/teuthology/buildpackages/tasks/tag.yaml, tasks/buildpackages.py, tasks/buildpackages/common.sh, tasks/buildpackages/make-deb.sh, tasks/buildpackages/make-rpm.sh, tasks/tests/test_buildpackages.py
The install config may have contradicting tag/branch and sha1.  When
suite.py prepares the jobs, it always overrides the sha1 with whatever
default is provided on the command line with --distro and what is found
in the gitbuilder. If it turns out that the tag or the branch in the
install config task is about another sha1, it will override anyway.
Instead of obtaining the tag, branch and sha1 directly from the
packaging.GitbuilderProject object, compute them from the returned
uri_reference data member. The uri_reference is used by the install task
to fetch packages in the gitbuilders and this is what buildpackages
needs to build.
=> buildpackages: honour install priorities tags, branch, sha1

tasks/buildpackages.py
os_version is from the remote and will be 7.1.23 for CentOS 7
instead of the expected 7.0 for all 7.* CentOS.
=> buildpackages: use _get_version instead of os_version

tasks/radosgw_admin.py
when testing radosgw-admin log show --object, don't use these objects
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>
=> radosgw_admin: skip log objects that start with obj_delete_at_hint

tasks/buildpackages/common.sh, tasks/buildpackages/make-deb.sh, tasks/buildpackages/make-rpm.sh
Prior to v0.80.9, autogen.sh did not get submodules. Copy/paste the
submodule initialization from newer autogen.sh in common.sh so that
v0.80.8 and below can be rebuilt from sources. It does not hurt to
update the submodules twice.
=> buildpackages: get ceph submodules

tasks/admin_socket.py
When running on virtual machines, it may take more than one minute for a
daemon to create the admin socket.
http://tracker.ceph.com/issues/13449 Fixes: #13449
=> tasks/admin_socket.py: wait 120 seconds instead of 60

suites/rados/singleton-nomsgr/all/msgr.yaml
If given only 8GB RAM,  ceph_test_msgr may abort with buffer::bad_alloc.
http://tracker.ceph.com/issues/11260 Fixes: #11260
=> rados/singleton-nomsgr/all/msgr: needs 15GB RAM

suites/upgrade/hammer-x/stress-split/0-cluster/start.yaml
The large number of OSDs is only needed for LRC or SHEC in some
cases. All other jobs will do fine with six OSDs.
http://tracker.ceph.com/issues/13408 Fixes: #13408
=> upgrade/stress-split: needs only six OSDs

suites/rgw/multifs/tasks/rgw_bucket_quota.yaml, suites/rgw/multifs/tasks/rgw_user_quota.yaml
The Amazon/S3.pm perl module from CPAN is not available as an RPM.
=> rgw: do quota tests on ubuntu

distros/supported/centos_7.0.yaml, distros/supported/debian_7.0.yaml, distros/supported/ubuntu_12.04.yaml
=> hammer now only supports CentOS 7 and Ubuntu 14.04

suites/rados/thrash/clusters/openstack.yaml
The thrasher needs disk attached to run against xfs, ext4 or btrfs. And
some jobs use more disks and do not fit in 40GB.
http://tracker.ceph.com/issues/13450 Fixes: #13450
=> openstack: rados/thrash: allocate three disks, always

suites/rados/objectstore/alloc-hint.yaml
So they can be mkfs xfs.
http://tracker.ceph.com/issues/13451 Fixes: #13451
=> rados/objectstore/alloc-hint: need three attached disks

suites/fs/basic/tasks/cfuse_workunit_kernel_untar_build.yaml
@jcsp @dachary 
Testing now as
<pre>
teuthology-suite -v -c hammer -m openstack -s fs -k distro -p 70 --suite-branch wip-openstack-fixes-fs_hammer -e yweinste@redhat.com --filter="fs/basic/{clusters/{fixed-3-cephfs.yaml openstack.yaml} debug/mds_client.yaml fs/btrfs.yaml inline/no.yaml overrides/whitelist_wrongly_marked_down.yaml tasks/cfuse_workunit_kernel_untar_build.yaml}"
</pre>
http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2015-10-20_18:16:50-fs-hammer-distro-basic-openstack/
=> Added openstack.yaml config

tasks/ceph_deploy.py
The existing logic is to ceph-deploy osd create --zap-disk which will
zap the data device before preparing it. However it will not zap the
journal device (see http://tracker.ceph.com/issues/13291).
If ceph-deploy osd create fails, a fall back will zap both the data
device and the journal and try prepare again. This could work if
the device preparation and activation was synchronous and catch all
errors that could be caused by an unclean journal device. However,
the activation is asynchronous and it is entirely possible for a device
to be prepared successfully and fail to activate in the background.
The data and journal device are always zapped before calling ceph-deploy
osd create. The logic is simpler and the overhead is low.
http://tracker.ceph.com/issues/13000 Fixes: #13000 …
=> ceph-deploy: always zap disk before creating an osd

tasks/buildpackages/common.sh
A clone of Ceph is not automagically updated with the tags from the
official Ceph repository. For a pull request based on master, git
describe will use whatever tags existed at the time the clone was made,
unless the author pull them from the official Ceph repository and later
git push --tags them.
The output of git describe is used to name the packages and if the
official tags are not present, the packages will be incorrectly
named. For instance instead of 9.0.3-34 the packages could be named
0.87-8433 because the v0.87 tag is the most recent tag in the
repository. That confuses the install task that will fail with:
'ceph version 0.87 was not installed, found 9.0.3.'
=> buildpackages: fetch tags from the official Ceph repository

tasks/buildpackages/Makefile
(cherry picked from commit 7b8f205952d5e49609efbd77a1becae3aff4e531)
=> buildpackages: silently ignore IPv6 addresses

suites/upgrade/client-upgrade/hammer-client-x/basic/1-install/hammer-client-x.yaml, suites/upgrade/client-upgrade/hammer-client-x/basic/2-workload/rbd_api_tests.yaml, suites/upgrade/client-upgrade/hammer-client-x/basic/2-workload/rbd_cli_import_export.yaml
Avoid attempting to test new release features that are not available
on older hammer OSDs.
Fixes: #13304
=> client-upgrade: hammer-based test should be used on new client

tasks/buildpackages.py
(cherry picked from commit 129c5db6c9bc41faa5c52df340776f00ab2db2b6)
=> buildpackages: 10GB is too small most of the time

tasks/buildpackages/make-rpm.sh
Older versions of Ceph have that problem failing would break all upgrade suites.
=> buildpackages: do not fails for unpackaged files

tasks/buildpackages.py, tasks/buildpackages/Makefile, tasks/buildpackages/common.sh, tasks/buildpackages/make-deb.sh, tasks/buildpackages/make-rpm.sh
Most of the flavor, sha1, tag etc. selection logic as implemented in the
packaging module of teuthology relies on remote hosts. This is complex
to tests and inconvenient because hosts must be provisionned even before
trying to figure out which packages need to be installed.
Using remote hosts is necessary when bare metal targets are used because
teuthology must adapt to the operating system already installed. The
selection logic in the context of dynamically provisionned targets is
simpler because it is defined by the job being run.
The buildpackages is refactored to use only the job configuration to
figure out which packages must be built. It makes it specific to targets
that are dynamically provisionned. It would have to be modified to query
the remote host in the case of bare metal …
=> buildpackages: refactor to not require remote

tasks/buildpackages.py, tasks/buildpackages/Makefile
It can be deprectated when it is implemented in teuthology.
=> buildpackages: implement get_pkg_type & avoid duplicate packages-repository

suites/rbd/qemu/clusters/openstack.yaml, suites/rbd/thrash/clusters/openstack.yaml
The thrasher and qemu need disk attached to run against xfs or btrfs,
otherwise it will use the local file system which is always ext4. It
will succeed but this is a kind of false positive since no xfs or btrfs
related tests were run.
http://tracker.ceph.com/issues/13270 Refs: #13270
(cherry picked from commit 29973822f8f21044026055a5fd216c3a96ba7eaf)
=> openstack: rbd/{thrash,qemu}: allocate three disks, always

suites/rbd/qemu/clusters/openstack.yaml, suites/rbd/thrash/clusters/openstack.yaml
The thrasher needs disk attached to run against xfs or btrfs, otherwise
it will use the local file system which is always ext4. It will succeed
but this is a kind of false positive since no xfs or btrfs related tests
were run.
=> openstack: rbd/thrash: allocate three disks, always

tasks/ceph_manager.py
The ceph pg scrub ... command isn't really guarranteed to
start a scrub, keep reissuing it until the scrub actually
happens.
Related: #12746
=> ceph_manager: do_pg_scrub: keep scrubbing until it's done

debug/openstack-30G.yaml
So that it can be used as follows:
teuthology-openstack ... --suite mysuite ... debug/openstack-30G.yaml
=> openstack: add 30GB for debugging purposes

tasks/cephfs/test_scrub_checks.py
Use named error codes instead of numbers, and
use the helper fn for getting inode number
instead of doing it by hand.
=> tasks/cephfs: tidy test_scrub_checks

debug/openstack-15G.yaml
So that it can be used as follows:
teuthology-openstack ... --suite mysuite ... debug/openstack-15G.yaml
=> openstack: add 15GB for debugging purposes

tasks/buildpackages/Makefile
When the quotas are low, it matters to block until the build machine is
actually deleted. Otherwise target provisionning may fail because the
they exceed the quota. For instance the default on OVH is to have 32
cores and the build machine uses 16. The packages-repository machine
uses two, the teuthology cluster uses one and that leaves only 13 cores
for the targets which may be too low when running jobs that require
large instances.
=> buildpackages: wait for the build machine deletion

tasks/rbd_fio.py
Similar to what the teuthology install.py task does, add --force-yes to
the apt-get install so that unsigned packages are successfully
installed. It is needed when the buildpackages task is used to create
packages on the fly.
There is no need to do the same for rpm packages because the
verification is controlled from the ceph-release package instead of from
the command line.
http://tracker.ceph.com/issues/13899 Fixes: #13899
=> task/rbd_fio: allow for unsigned packages

tasks/buildpackages.py
Since buildpackages runs before target provisioning, it is possible that
the desired image does not yet exist on a newly provisionned tenant (or
region).
http://tracker.ceph.com/issues/13910 Fixes: #13910
=> buildpackages: create the image if it does not exist

suites/upgrade/infernalis/point-to-point/distros, suites/upgrade/infernalis/point-to-point/ubuntu_14.04.yaml
The upgrade suite is supposed to run on all supported distros.
http://tracker.ceph.com/issues/13908 Fixes: #13908
=> upgrade/infernalis: run on supported distros

suites/fs/recovery/tasks/forward-scrub.yaml, tasks/cephfs/test_forward_scrub.py
This tests the forward scrub's ability to traverse
some metadata and tag it, and the corresponding
functionality in cephfs-data-scan to filter based
on tag and inject orphaned items.
=> tasks/cephfs: add TestForwardScrub

suites/teuthology/workunits/yes.yaml, tasks/workunit.py
The commit from which workunits must be fetched must be retrieved
from --ceph-git-url via teuth_config.get_ceph_git_url() instead of
assuming it is available via git://git.ceph.com/ceph.git.
Assuming git://git.ceph.com/ceph.git is convenient because it
supports git archive. In the general case, some git servers such as
github do not support git archive and a full git clone must be done.
Although it would be possible to
git clone --branch=master --depth=1 --single-branch
to reduce the amount of data being retrieved, it would require a
git fetch origin SHA1
but git version >= 1.7 require a refspec and do not support fetching
a commit.
http://tracker.ceph.com/issues/13624 Fixes: #13624
=> workunits: fetch from --ceph-git-url

suites/rados/thrash-erasure-code/workloads/ec-radosbench.yaml, suites/rados/thrash/workloads/radosbench.yaml, suites/rados/upgrade/hammer-x-singleton/7-workload/radosbench.yaml
The smithi disks fill after about 20m.
=> rados: run radosbench for 15m instead of 30m

tasks/cephfs/test_damage.py
When stray directory inodes are corrupted, MDS may go to damaged state
after becoming active. (MDCache::open_root/populate_mydir is called by
MDSRank::starting_done).
Fixes: #14196
=> tasks/cephfs: fix race in test_damage

tasks/cephfs/test_client_recovery.py
make sure fsync wait for unsafe requests that created/modified the
file.
=> cephfs/test_client_recovery: check fsync waits for unsafe requests

tasks/cephfs/filesystem.py
Return actual elapsed wallclock time instead of
the number of times we polled.
Fixes: #14257
=> tasks/cephfs: fix wait_for_state timing

suites/rbd/valgrind/validator/helgrind.yaml, suites/rbd/valgrind/validator/memcheck.yaml, suites/rbd/valgrind/workloads/fsx.yaml, suites/rbd/valgrind/workloads/fsx_helgrind.yaml, tasks/rbd_fsx.py
Allow rbd_fsx to accept an override for which valgrind tool to use.
=> suites/rbd: avoid redundant helgrind tests

suites/rbd/thrash/workloads/rbd_nbd.yaml
NBD support is not available in RHEL/CentOS 7
=> rbd: rbd-nbd can only run on Ubuntu

suites/fs/recovery/tasks/cap-flush.yam, tasks/cephfs/test_cap_flush.py
=> tasks/cephfs: test for race between cap flush and clientreplay

tasks/cephfs/vstart_runner.py
Previously teuthology read test path from ctx.teuthology_config,
now it reads it from the global teuthology.config.config object.
This was breaking test_journal_migration because it uses tasks/workunit,
when run with vstart_runner.
=> tasks/cephfs: update vstart_runner for teuthology change

tasks/cephfs/test_full.py
When it gives an error from the unexpected place,
say so.
=> tasks/cephfs: better message from test_full_fsync

suites/upgrade/firefly-hammer-x/parallel/0-cluster/start.yaml, suites/upgrade/infernalis/older/0-cluster/start.yaml, suites/upgrade/infernalis/older/1-install/latest_hammer_release.yaml, suites/upgrade/infernalis/older/1-install/v9.2.0.yaml, suites/upgrade/infernalis/older/2-workload/s3tests.yaml, suites/upgrade/infernalis/older/2-workload/testrados.yaml
@liewegas 
@tmuthamizhan 
Added s3tests workload
Fixed initial version to be 'hammer'
Added v9.2.0 to the mix
Note: whitelisted 'failed to encode map'
@tmuthamizhan I removed v9.1.0.yaml as it looks like only v9.2.0 was officially infernalis release, but need you to confirm this assessment.
(added `+` to run all workloads together sequentially )
=> Fixes issue #14389

suites/upgrade/firefly-x/stress-split/0-cluster/start.yaml
soft lockup
detected stalls on CPUs
to avoide failures in ovh
@jdurgin FYI
=> Whitelisted

tasks/cephfs/test_client_recovery.py
Mostly checking the output from the status asok is awkward
because you need to get the system stuck in a particular
state to do so.  However, we already have a test here
that sticks the system in reconnect, so here's some
very light test coverage for that asok.
=> tasks/cephfs: check status asok output while in reconnect

tasks/cram.py
=> cram: pin to version 0.6 because 0.7 handles \r differently

tasks/scrub_test.py
* rados cli prints "head" at seeing CEPH_NOSNAP, so update the test
accordingly
* print inconsistent objs before testing them
Fixes: #14924
=> tasks/scrub_test: match the NOSNAP with "head"

suites/ceph-ansible/smoke/2-setup/ceph_ansible.yaml
3x20GB per instance
Signed-off-by: Zack Cerza <zack@redhat.com>
=> ceph-ansible: Add openstack hints for volumes

tasks/ceph_manager.py
We were doing this for one of the recovery timeouts but not all of them.
=> tasks/ceph_manager: dump pgs if other peering timeouts expire

suites/rados/singleton-nomsgr/all/11429.yaml
The newer cephfs logic wants to use the 'status' command on the
daemon, but that doesn't exist on firefly.  Luckly we don't need
it for this test.
=> rados/singleton-nomsgr/all/11429: no mds

tasks/cephfs/fuse_mount.py, tasks/cephfs/vstart_runner.py
A couple of corner cases that would get tripped up sometimes
in a vstart_runner.py environment.
=> tasks/cephfs: vstart & fuse improvements

suites/rados/singleton-nomsgr/all/cache-fs-trunc.yaml, tasks/cephfs/filesystem.py
While Filesystem at large requires the new commands, for
use from the `ceph` task we must support old style commands,
as the ceph task is used to instantiate old clusters during
upgrade testing.
Fixes: #15124, #15049, #15106
=> tasks/cephfs: support old mdsmap command during setup

suites/rados/singleton-nomsgr/all/13234.yaml, suites/rados/singleton-nomsgr/all/full-tiering.yaml, suites/rados/singleton-nomsgr/all/valgrind-leaks.yaml, suites/rados/upgrade/hammer-x-singleton/0-cluster/start.yaml
These daemons were apparently unused in tests that
created an MDS daemon but never use a fuse task
to access it.
=> suites: remove unused mdss from RADOS tests

tasks/ceph.py
=> tasks/ceph.py: Remove *.pid at end of run

suites/upgrade/infernalis-x/stress-split/5-workload/rbd-cls.yaml, suites/upgrade/infernalis-x/stress-split/5-workload/rbd-import-export.yaml, suites/upgrade/infernalis-x/stress-split/7-workload/rbd_api.yaml, suites/upgrade/infernalis-x/stress-split/9-workload/rbd-python.yaml
There are only few differences at the moment but it may be confusing
later on if a bug is fixed in the infernalis workunits later on.
=> upgrade: use infernalis instead of hammer for rbd tests

suites/powercycle/osd/tasks/radosbench.yaml, suites/rados/thrash-erasure-code/workloads/ec-radosbench.yaml, suites/rados/thrash/workloads/radosbench.yaml, suites/rados/upgrade/hammer-x-singleton/7-workload/radosbench.yaml, suites/smoke/basic/tasks/rados_bench.yaml, suites/upgrade/firefly-hammer-x/stress-split/07-workload/radosbench.yaml, suites/upgrade/firefly-hammer-x/stress-split/19-workload/radosbench.yaml, suites/upgrade/hammer-x/stress-split/7-workload/radosbench.yaml, suites/upgrade/infernalis-x/stress-split/7-workload/radosbench.yaml
If we want a longer runtime than that, run it several times in
sequence.
This limits the amount of disk space we'll consume.
=> suites: run rados bench for max 180 seconds

suites/upgrade/infernalis-x/parallel/0-cluster/openstack.yaml, suites/upgrade/infernalis-x/point-to-point-x/point-to-point.yaml, suites/upgrade/infernalis-x/stress-split/0-cluster/openstack.yaml
The intention is to run with xfs which requires a separate disk for each
OSD. In addition the tests will exhaust the available root disk space
otherwise.
http://tracker.ceph.com/issues/15236 Fixes: #15236
=> upgrade/infernalis-x: allocate OpenStack volumes for each OSD

tasks/radosbench.py
A run failed due to thrashing.. missed by about 30s (the osd
eventually sent the last reply but we'd already timed out).
(cherry picked from commit 3e30d5dfdf823b345a6ded71e32e016e4e7d1396)
=> tasks/radosbench: wait just a bit longer

suites/upgrade/hammer-x/parallel/2-workload/blogbench.yaml, suites/upgrade/infernalis-x/parallel/2-workload/blogbench.yaml, suites/upgrade/infernalis-x/parallel/2-workload/ec-rados-default.yaml
Fixes #15093
Note: sequential and full_sequential (dictionary) can't be both under parallel stanza
=> Added blogbench.yaml to parallel before and after -x upgrade steps

suites/rados/thrash/thrashers/morepggrow.yaml
=> morepggrow: enable filestore and journal soft backoffs

tasks/radosgw_admin.py
We have to use zone name because we cannot configure a default zone when there is no realm
=> rgw: add default zone name

tasks/rgw.py
=> rgw: use civetweb if no frontend was configured

tasks/ceph.py, tasks/cephfs/test_data_scan.py, tasks/cephfs/test_failover.py, tasks/cephfs/test_journal_repair.py, tasks/cephfs/test_sessionmap.py, tasks/cephfs/test_strays.py
We've disabled certain FS behaviors by default and need to turn them on when testing.
=> cephfs: update tests to enable multimds when needed

tasks/cephfs/cephfs_test_case.py, tasks/cephfs/test_auto_repair.py
=> tasks/cephfs: test health messages from readonly stat

tasks/cephfs/filesystem.py, tasks/cephfs/test_volume_client.py
NS is always used for security isolation.
Signed-off-by: Xiaoxi Chen <xiaoxchen@ebay.com>
=> tasks/cephfs: check data written to NS.

suites/fs/recovery/clusters/4-remote-clients.yaml, suites/fs/recovery/mounts/ceph-fuse.yaml, tasks/cephfs/mount.py, tasks/cephfs/test_volume_client.py, tasks/cephfs/vstart_runner.py
Test whether the CephFSVolumeClient can evict a client based on its
auth ID and the volume path it has mounted.
Fixes: http://tracker.ceph.com/issues/15045
Signed-off-by: Ramana Raja <rraja@redhat.com>
=> tasks/cephfs: test volume client eviction

tasks/cephfs/test_volume_client.py
Signed-off-by: Xiaoxi Chen <xiaoxchen@ebay.com>
=> fs/volume_client: exercise the configurable prefix and ns_prefix.

suites/rados/thrash/workloads/small-objects.yaml
Legacy tunables semi-frequently turn up crush mappings that only
return 1 instead of 2 results.  Switch to covering jewel tunables
explicitly instead.
=> rados: test jewel instead of legacy tunables

nightlies/cron_wrapper
@jdurgin @dmick Pls review and merge
Next:
use this script in sepia and ovh labs for all nightlies schedules 
Fixes: http://tracker.ceph.com/issues/15563
=> A script to be used in crontab sepia/ovh labs, so emails sent only on errors, logs stored 

suites/rados/thrash/workloads/readwrite.yaml
In ceph.git i propose "PG: no need to judge op_is_discardable after op has been dequeued" https://github.com/ceph/ceph/pull/8717
Here to test the parameter osd_discard_disconnected_ops
=> suites/rados: test osd_discard_disconnected_ops

tasks/cephfs/filesystem.py, tasks/cephfs/test_failover.py
Previously, an MDS could be used as a replay even
if it had "standby replay = false", this is changed
now so that replays will only happen explicitly.
=> tasks/cephfs: update failover test for standby changes

tasks/cephfs/test_sessionmap.py
Now that daemon commandlines include "--cluster" they
easily overflow ps's default behaviour.
Fixes: http://tracker.ceph.com/issues/15857
=> tasks/cephfs: fix ps usage to not truncate cmds

mon_kv_backend/leveldb.yaml, mon_kv_backend/rocksdb.yaml, suites/rados/basic/mon_kv_backend, suites/rados/monthrash/mon_kv_backend, suites/rados/multimon/mon_kv_backend, suites/rados/thrash-erasure-code-big/leveldb.yaml, suites/rados/thrash-erasure-code-isa/leveldb.yaml, suites/rados/thrash-erasure-code-shec/leveldb.yaml, suites/rados/thrash-erasure-code/leveldb.yaml, suites/rados/thrash/rocksdb.yaml, suites/rados/verify/mon_kv_backend
Use just rocksdb for thrash to avoid blowing up the matrix.  Leave
leveldb for the ec thrash suites.
=> rados: vary mon kv backend

tasks/cephfs/test_volume_client.py
For reproducing error handling paths during purge,
such as #15266 (ASCII exception)
Fixes: http://tracker.ceph.com/issues/15266
=> tasks/cephfs: add TestVolumeClient.test_purge

tasks/scrub_test.py
This should fix the errors seen in the rados runs.
=> scrub_test: Shards are not marked in error when osd guesses

tasks/create_verify_lfn_objects.py
Signed-off-by: Josh Durgin <jdurgin@redhat.com>
(cherry picked from commit 1cb2681cd02d7782c9dea602c9cf2b0fb80e6fae)
it fixes two of the failed tests in http://pulpito.ceph.com/kchai-2016-05-30_20:29:54-rados-jewel---basic-smithi/223993/ 
- 223503
- 223522
=> tasks/create_verify_lfn_objects: adjust to new ctx.manager location

tasks/object_source_down.py, tasks/osd_backfill.py, tasks/osd_recovery.py, tasks/peer.py, tasks/recovery_bench.py, tasks/rep_lost_unfound_delete.py, tasks/scrub.py
CephManager has no sleep function. Use time.sleep() instead.
Ran into this while testing a branch. Apparently it doesn't happen
much since this hasn't changed in years, but the error was copied
into several tasks.
Signed-off-by: Josh Durgin <jdurgin@redhat.com>
=> tasks: fix non-existent sleep function

tasks/cephfs/vstart_runner.py
The message was printing loaded modules before loading each module.
=> vstart_runner: move info message for loaded mods

tasks/cephfs/vstart_runner.py
This prevents vstart_runner.py from trying to kill other user's ceph-mds/ceph-fuse instances.
=> vstart_runner: only kill/look at user's processes

tasks/cephfs/vstart_runner.py
Dropping the 'x' caused the ps lines not to include
the "-i <myid>" part of the command line that we use
to find named daemons' pids.
=> tasks/cephfs: fix vstart runner _get_pid

tasks/cephfs/test_sessionmap.py
Fixes test_mount_conn_close failure http://pulpito.ceph.com/teuthology-2016-05-22_02:10:01-fs-jewel---basic-smithi/207265/
=> (jewel) backport cephfs fixes for test broken by multi-cluster support

tasks/cephfs/test_failover.py
Previously, an MDS could be used as a replay even
if it had "standby replay = false", this is changed
now so that replays will only happen explicitly.
(cherry picked from commit d9309b57e3c12579f64939ee78161f7e99a062c8)
=> (jewel) tasks/cephfs: update failover test for standby changes

tasks/cephfs/cephfs_test_case.py
The new PR (https://github.com/ceph/ceph/pull/8737) will break some cephfs test cases due to the strict checking in wait_for_health function, which is not very necessary, I think. So I made some changes to this function to be more flexible.
Signed-off-by: Zhi Zhang <zhangz.david@outlook.com>
=> Adjust wait_for_health to be more flexible

tasks/mds_thrash.py
Previously, when there was an exception in the thrasher
main loop, it would log it but ultimately "succeed"
the teuthology task.
=> task/mds_thrash: don't drop exceptions from thrasher

tasks/ec_lost_unfound.py, tasks/lost_unfound.py
The upgrade tests restart the daemons right before that part, and the
restart marks the osds down causing the flush_pg_stats to fail.  It's
not necessary anymore anyway.
=> [ec_]lost_unfound: don't flush_pg_stats at the beginning

overrides/short_pg_log.yaml
=> short_pg_log: double params to avoid failures from dup detection failure

suites/ceph-deploy/basic/python_versions/python_2.yaml, suites/ceph-deploy/basic/python_versions/python_3.yaml, tasks/ceph_deploy.py
This is tightly related to https://github.com/ceph/ceph-deploy/pull/388 (Python 3 Compatibility of ceph-deploy).
- The changes to the QA suite are needed in order to test ceph-deploy under different Python versions (here only major versions are specified - 2 or 3). If the *python_version* is not specified, nothing will be installed and the default *python* executable will be used (basically old behavior).
- And in turn, this pull request relies on the change of the bootstrap script in ceph-deploy, and, of course, the Python 3 compatibility is the new feature that is tested here.
Here are some sepia test runs under these changes:
- http://pulpito.ceph.com/oprypin-2016-06-16_08:41:28-ceph-deploy-jewel---basic-mira/
- http://pulpito.ceph.com/oprypin-2016-06-17_10:12:39-ceph-deploy-jewel---bas …
=> tasks/ceph-deploy: Run on multiple Python versions (2, 3)

tasks/ceph_deploy.py
teuthology default override template defines devcommit which makes
'branch' overrides in the test useless since it only picksup one option
Remove the devcommit overrides from the template and use that as
default in case no other 'branch' override exist.
=> Fix for 'branch' overrides to work

tasks/scrub_test.py
This reverts commit 9e2b455f45cca2f31b19c73d761661a9028c22ff.
=> Revert "tasks/scrub_test: use fuse path (do not assume filestore!)"

suites/rados/thrash/workloads/cache-agent-big.yaml
Otherwise min_size will be 3 and we will wedge on a single down
osd.
=> rados/thrash/workloads/cache-agent-big: set min_size=2 on m=1 k=2 ec pool

suites/fs/basic/dirfrag/frag_enable.yaml, tasks/cephfs/test_strays.py
The fragment configuration uses 10000 for the fragment max size. The reason for
this is that many tests add 1000 files to a single directory which will hit
this limit without fragmentation catching up.
The test_dirfrag_limit test confirms:
o That the directory fragment size cannot exceed mds_bal_fragment_size_max (using a limit of 50 in all configurations).
o That fragmentation (forced) will allow more entries to be created.
o That unlink fails when the stray directory fragment becomes too large and that unlinking may continue once those strays are purged.
Tests: https://github.com/ceph/ceph/pull/9789
Issue: http://tracker.ceph.com/issues/16164
Signed-off-by: Patrick Donnelly <batrick@batbytes.com>
=> cephfs: test fragment size limit

tasks/ceph_manager.py, tasks/ec_lost_unfound.py
We changed the default to k+1 instead of k.  Adjust test to compensate.
Fixes: http://tracker.ceph.com/issues/16416
=> ec_lost_unfound: set min_size to 2

suites/rados/singleton-nomsgr/all/11429.yaml
ceph.restart now marks the osds down, so the objects are actually being
created while slowest of the osds boots. That causes a ton of 1 byte
objects to be created in a degraded state and causes the cleanup to take
a long time.  Also, reduce length of bench since it's only being used
to ensure the osds came up correctly.
=> 11429: wait_for_clean between restarting the osds and starting the bench

packages/packages.yaml
Meant to be merged together with https://github.com/ceph/ceph/pull/10433
Fixes: http://tracker.ceph.com/issues/16808
Signed-off-by: Nathan Cutler <ncutler@suse.com>
=> packages/packages.yaml: drop ceph-fs-common-dbg

tasks/ceph_deploy.py
Use the newer stdout value for checking
ceph health again.
=> Fix rechecking of health in loop

tasks/cephfs/test_client_limits.py
Fortunately we already have a test that creates the condition,
so just tweak it to exceed the 150% threshold for the health warning,
and check that the health message appears.
=> tasks/cephfs: check cache size health warning

tasks/ceph_deploy.py
Use the newer stdout value for checking
ceph health again.
=> backport - Wip fix bad check 

packages/packages.yaml
The way we currently build the cephfs java
bindings depends on the unversioned .so file
which is in the -dev package, not the
main one.
Fixes: http://tracker.ceph.com/issues/16640
=> task/packages: install libcephfs1-dev

tasks/osd_recovery.py
(cherry picked from commit ddabdb7f722b192435b87bc31fe587b93cc53924)
Hopefully fixes intermittent failure: http://tracker.ceph.com/issues/16840
=> osd_recovery: add delay to ensure maps propogate

tasks/cephfs/vstart_runner.py
vstart_runner can't find arguments to ceph daemons to identify them with
ps -x because commands are cut off at terminal width. Add -w for wide
output.
Signed-off-by: Douglas Fuller <dfuller@redhat.com>
=> cephfs/vstart_runner: add -w option to ps

tasks/radosgw_admin.py
Fixes: http://tracker.ceph.com/issues/17025
(cherry picked from commit c6cdd0905fbb3a9571400a5227b34b7e2e738830)
=> rgw: data_extra_pool is unique per zone

suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
The v10.2.x cls_rbd test case will not pass against a v10.2.0
OSD. Disable the offending test.
Fixes: http://tracker.ceph.com/issues/16529
=> suites/upgrade: point-to-point Jewel upgrade workaround

tasks/ceph_manager.py
otherwise monitor could reject the command:
```
Refusing to reweight: we only used 588084 kb used across all osds!
```
if the average used space is smaller than
`mon_reweight_min_bytes_per_osd`.
Fixes: http://tracker.ceph.com/issues/16805
=> ceph_manager: lower mon_reweight_min_bytes_per_osd to 10

tasks/ceph_manager.py
Otherwise, all invokations share the *same* StringIO instance
leading to some very silly bugs.
=> ceph_manager: do not use StringIO instance as default argument

packages/packages.yaml
This reverts commit ec4b0c3d6b057e688363d966a83a037c3585b32f.
References: http://tracker.ceph.com/issues/17075
Signed-off-by: Nathan Cutler <ncutler@suse.com>
=> Revert "packages.yaml: reflect python-ceph package split"

tasks/workunit.py
When multiple client run in parallel on the same machine and they
try to get workunits from a repository that is not github, they must
git clone in a directory that is suffixed as srcdir. Otherwise they
will conflict with each other.
Fixes: http://tracker.ceph.com/issues/17116
(cherry picked from commit b9813e490ec8a5bb59e177612f047899397c342e)
=> [DNM] workunit: allow parallel git clone

tasks/workunit.py
When multiple client run in parallel on the same machine and they
try to get workunits from a repository that is not github, they must
git clone in a directory that is suffixed as srcdir. Otherwise they
will conflict with each other.
Fixes: http://tracker.ceph.com/issues/17116
(cherry picked from commit b9813e490ec8a5bb59e177612f047899397c342e)
=> workunit: allow parallel git clone

suites/krbd/unmap/clusters/fixed-1.yaml, suites/krbd/unmap/clusters/separate-client.yaml
Otherwise a pre-single-major kernel override is a headache,
particularly with non-standard yaml configs.
=> krbd/unmap: put client.0 on a separate remote

suites/rados/singleton-nomsgr/all/11429.yaml
to make sure that load_pgs() is finished before checking its output
Fixes: http://tracker.ceph.com/issues/16157
=> rados/singleton-nomsgr/all/11429: wait until clean before checking log

suites/fs/basic/tasks/cfuse_workunit_kernel_untar_build.yaml
Ported from Zheng's #22: 2e283ce6d77c66a564d807f0b0909b238c4fb5f0
"This can reduce the test time becuase it avoids sending getattr request
whenever the kernel checks inode permission."
This is part of an effort to eliminate unnecessary differences between
multimds and fs suites.
Signed-off-by: Patrick Donnelly <batrick@batbytes.com>
=> fs: fuse_default_permissions = 0 for kernel build test

tasks/ceph.py
Previously, if errors occurred during healthy(), then
the finally block would invoke osd_scrub_pgs, which relies
on CephManager being constructed, and it would die, hiding
the original exception.
=> tasks/ceph: construct CephManager earlier

tasks/ceph_manager.py
When killing an osd, split all pools with a low threshold.
This will slow down tests, but should not impact correctness.
This requires https://github.com/ceph/ceph/pull/10776
=> ceph_manager: test offline split via ceph-objectstore-tool

suites/upgrade/client-upgrade/hammer-client-x/basic/1-install/hammer-client-x.yaml
Do not exclude the ceph-test package otherwise the ceph-coverage
executable is not installed.
Fixes: http://tracker.ceph.com/issues/16506
=> upgrade: ceph-test is needed for ceph-coverage

suites/rados/singleton/all/rebuild-mondb.yaml, tasks/ceph_manager.py, tasks/rebuild_mondb.py
* tasks/rebuild_mondb.py: this task
1. removes all store.db on all monitors
2. rebuild the store.db for the first mon
3. start the first mon
4. run mkfs on other mon
5. and revive them
* suites/rados/singleton/all/rebuild-mon-db.yaml
1. run rados/test.sh
2. run rebuild_mondb task
Fixes: http://tracker.ceph.com/issues/17179
=> tasks: add rebuild_mondb

suites/rbd/valgrind/validator/helgrind.yaml
Helgrind cannot properly handle Ceph's use of std::mutex --
resulting in numerous false positives and potential assertion
failures.
=> suites/rbd: remove helgrind test cases

suites/rbd/valgrind/validator/helgrind.yaml
Helgrind cannot properly handle Ceph's use of std::mutex --
resulting in numerous false positives and potential assertion
failures.
(cherry picked from commit b29bf9253d7d2201f4cf01b0fd6997ed1bae231f)
=> jewel: suites/rbd: remove helgrind test cases

suites/ceph-deploy-release/distros, suites/ceph-deploy-release/overrides/ceph_deploy_dmcrypt.yaml, suites/ceph-deploy-release/overrides/disable_diff_journal_disk.yaml, suites/ceph-deploy-release/tasks/release-install-test.yaml
simple test suite to test ceph from download.ceph.com (with stable: jewel flag)
@alfredodeza  @ktdreyer ping
http://pulpito.ceph.com/vasu-2016-09-21_20:31:36-ceph-deploy-release-jewel---basic-vps/ ,
Fixed one config issue in this run
http://pulpito.ceph.com/vasu-2016-09-21_21:14:05-ceph-deploy-release-jewel---basic-vps/ 
=> Add ceph-deploy tests for released builds

tasks/dump_stuck.py
There seem to be two problems: one is that the mon's 'pg dump_stuck ...' result
isn't coherent with the health warning.  This is fixed by a ceph commit in
https://github.com/ceph/ceph/pull/11339.  The other is that this test
didn't account for the fact that when the OSDs went down the PGs would also
appear unclean because they OSDs may not fail simultaneously.  That used
to be a hard case to trigger, but with the RST markdown it happens in the
normal case. We adjust this test so that it reliably happens and then
also assert that PGs are unclean.
=> tasks/dump_stuck: fix failure

suites/fs/32bits/tasks/cfuse_workunit_suites_pjd.yaml, suites/fs/basic/tasks/cfuse_workunit_suites_pjd.yaml, suites/fs/permission/tasks/cfuse_workunit_suites_pjd.yaml, suites/fs/thrash/tasks/cfuse_workunit_suites_pjd.yaml, suites/marginal/multimds/tasks/workunit_suites_pjd.yaml, suites/multimds/basic/tasks/suites_pjd.yaml, suites/powercycle/osd/tasks/cfuse_workunit_suites_pjd.yaml, suites/smoke/basic/tasks/cfuse_workunit_suites_pjd.yaml
As we improve our security model, we need to test it instead of the kernel.
=> fs: enable ceph-fuse permission checking for all pjd suites

suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
Upgrade happens in parallel with cls_rbd test run which can result in
a false-positive test failure.
=> suites/upgrade: additional point-to-point Jewel upgrade workaround

suites/rados/basic/tasks/readwrite.yaml
The thrash matrix includes min_size = 2 and size = 2.  This
is fine and good, except that the inevitable slow rados ops
that generates make readwrite.yaml issue timeouts and
fail.  Since the workload isn't meant to tolerate slow
requests, move it into the basic/ group.
=> rados: move readwrite test out of thrash matrix

tasks/rebuild_mondb.py
we will fail 'ceph-monstore-tool' command if the caps is empty so user
won't assign a key without any caps when rebuilding the monstore.
=> tasks/rebuild_mondb.py: fill up the caps in the keyring

suites/rados/singleton/all/osd-recovery-incomplete.yaml, suites/rados/singleton/all/osd-recovery.yaml
This test relies on being able to kill two OSDs before
they detect the failures on their own.
=> rados/singleton/all/osd-recovery*: disable fast fail

tasks/cephfs/test_volume_client.py
Check that the total size shown by the df output of a mounted volume
is same as the volume size and the quota set on the volume.
=> test_volume_client: check volume size

tasks/ceph.py
This was only used in this task, and it is much too
ceph-specific to belong in teuthology.
Fixes: http://tracker.ceph.com/issues/17614
=> tasks/ceph: move generate_caps from teuthology

suites/rados/singleton/all/mon-seesaw.yaml, tasks/mon_seesaw.py
mon_seesaw task replaces a monitor with a newly reployed one, in a
single-mon test including this task OSDs will not be able to connect
to cluster if the tracker#17558 is not fixed on the monitor side.
http://tracker.ceph.com/issues/17558
=> mon-seesaw: add mon-seesaw test and mon_seesaw task

tasks/scrub_test.py
epoch keys also exist in the objs dump, count only
inconsistent objects
=> assert based on inconsistent objects count instead of all keys

suites/rgw/verify/tasks/rgw_s3tests.yaml
This change aims to test rgw with messenger failure injection
and very short logs.
Signed-off-by: Tamil Muthamizhan <tmuthami@redhat.com>
=> Added short pg log entries to rgw test

suites/rados/upgrade/jewel-x-singleton/1-jewel-install/jewel.yaml
=> rados/upgrade: skip ceph-mgr on jewel install

packages/packages.yaml
Companion patchset to the pull request here:
https://github.com/ceph/ceph/pull/11647
Basically, we're changing the version of libcephfs so we need to update ceph-qa-suite accordingly.
=> libcephfs1 -> libcephfs2 rename

suites/rados/singleton/all/radostool.yaml
There's a k=2 m=1 ec pool in the test!
Fixes: http://tracker.ceph.com/issues/17775
=> rados/singleton: need 3 osds for radostool test

packages/packages.yaml
fixes http://pulpito.ceph.com/kchai-2016-11-11_07:45:56-rados-wip-kefu-testing---basic-smithi/539297/
```
2016-11-11T08:00:59.253 DEBUG:teuthology.task.install:Excluding packages: ['ceph-mgr', 'libcephfs2']
2016-11-11T08:00:59.253 DEBUG:teuthology.task.install:Package list is: {'deb': ['ceph-mds', 'rbd-fuse', 'librbd1', 'ceph-fuse', 'python-ceph', 'ceph-common', 'libcephfs-java', 'ceph', 'libcephfs-dev', 'ceph-test', 'radosgw', 'librados2', 'libcephfs-jni'], 'rpm': ['libcephfs_jni1', 'rbd-fuse', 'ceph-radosgw', 'librbd1', 'ceph-fuse', 'python-ceph', 'ceph', 'ceph-test', 'librados2', 'cephfs-java', 'libcephfs2-devel']}
...
2016-11-11T08:08:12.729 INFO:teuthology.orchestra.run.smithi095:Running: "sudo yum -y install '' libcephfs2-devel"
2016-11-11T08:08:12.990 …
```
=> packages: s/libcephfs2-devel/libcephfs-devel/

suites/upgrade/hammer-x/stress-split/8-next-mon/monc.yaml
It was missing and the cluster permanently stays on WARNING state after
the upgrade of the OSDs.
=> upgrade/hammer-x/stress-split: set require_jewel_osds

suites/rgw/singleton/all/radosgw-admin-data-sync.yaml, suites/rgw/singleton/all/radosgw-admin-multi-region.yaml, suites/rgw/verify/tasks/rgw_s3tests_multiregion.yaml, tasks/rgw.py, tasks/util/rgw.py
Startup races are the root cause of several failures in the rgw suite. Teuthology's daemon framework doesn't allow us to block until the daemon finishes startup, so we've added sleeps to account for this. But there are cases where `radosgw` and `radosgw-agent` instances take over a minute to start, so the sleeps of 5-20 seconds are insufficient (and raising their durations would be wasteful in most cases).
This PR replaces these sleeps with http requests that poll the daemon with retry/backoff until it starts accepting connections. For `radosgw`, this happens at the end of `start_rgw()`. For `radosgw-agent`, it just adds retry/backoff to the http requests we're already sending.
Fixes: http://tracker.ceph.com/issues/16129
Fixes: http://tracker.ceph.com/issues/17794
Fixes: …
=> rgw: fix some races with radosgw and radosgw-agent startup

tasks/rgw.py
flake8 was failing.
Signed-off-by: Owen Synge <osynge@suse.com>
=> tasks.rgw: 'time' imported but unused

suites/upgrade/hammer-x/parallel/0-cluster/start.yaml, suites/upgrade/hammer-x/parallel/3-upgrade-sequence/upgrade-osd-mds-mon.yaml, suites/upgrade/hammer-x/v0-94-4-stop/ignore.yaml
We should avoid these messages now.
=> upgrade/hammer-x: do not whitelist 'failed to encode map'

tasks/ceph_manager.py
If ceph-objectstore-tool binary is not present, it's likely because we're in
the middle of an upgrade. Look for the binary for up to one minute instead of
just running it and failing with "exec: ceph-objectstore-tool: not found".
Fixes: http://tracker.ceph.com/issues/18014
Signed-off-by: Nathan Cutler <ncutler@suse.com>
=> thrashosds: try ceph-objectstore-tool for one minute

suites/knfs/basic/ceph/base.yaml
Workaround for http://tracker.ceph.com/issues/16397, which
manifests when we run bleeding edge kernels against the version
of nfs-utils in centos7.
=> suites/knfs: pin to ubuntu

suites/rados/objectstore/objectstore.yaml
Avoid breaking rados suite while we are developing rapidly.
Signed-off-by: Sage Weil sage@redhat.com
(cherry picked from commit 11ee1a8cfdc85855df06375d56f741a3186db08d)
=> rados/objectstore/objectstore.yaml: skip bluestore tests

suites/rados/thrash-erasure-code-big/thrashers/default.yaml, suites/rados/thrash-erasure-code-big/thrashers/fastread.yaml, suites/rados/thrash-erasure-code-big/thrashers/morepggrow.yaml, suites/rados/thrash-erasure-code-shec/thrashers/default.yaml, suites/rados/thrash-erasure-code/thrashers/default.yaml, suites/rados/thrash-erasure-code/thrashers/fastread.yaml, suites/rados/thrash-erasure-code/thrashers/mapgap.yaml, suites/rados/thrash-erasure-code/thrashers/morepggrow.yaml, suites/rados/thrash-erasure-code/thrashers/pggrow.yaml, suites/rados/thrash/thrashers/default.yaml, suites/rados/thrash/thrashers/mapgap.yaml, suites/rados/thrash/thrashers/morepggrow.yaml, suites/rados/thrash/thrashers/pggrow.yaml
This can lead to a copy-from vs backfill deadlock; see
http://tracker.ceph.com/issues/18085
This effectively reverts 5e880228fd7f59063d22a51eb5488b369b0c8360
which aimed to catch bugs in recovery reservations.
=> rados/thrash*: do no set osd_max_backfills=1

tasks/qemu.py
Hack until fix in https://bugzilla.redhat.com/show_bug.cgi?id=1333159 makes it into CentOS repos.
http://pulpito.ceph.com/dgalloway-2016-11-29_00:02:41-rbd-wip-ec-partial-overwrites---basic-smithi/
Signed-off-by: David Galloway <dgallowa@redhat.com>
=> qemu: Set permissions on /dev/kvm

suites/krbd/unmap/kernels/pre-single-major.yaml
3.13 won't build on newer distros, due to lack of gcc5 support.
nightly/pre-single-major (with a slash) is now gone.
=> krbd/unmap: pre-single-major is now 3.12.z

suites/fs/verify/validater/valgrind.yaml, suites/multimds/verify/validater/valgrind.yaml, suites/rados/singleton-nomsgr/all/valgrind-leaks.yaml, suites/rados/verify/validater/valgrind.yaml, suites/rbd/valgrind/validator/memcheck.yaml, suites/rgw/verify/tasks/rgw_s3tests.yaml, suites/rgw/verify/tasks/rgw_s3tests_multiregion.yaml, suites/rgw/verify/tasks/rgw_swift.yaml, suites/rgw/verify/validater/valgrind.yaml
The xenial valgrind has a bug with generating random
numbers; see http://tracker.ceph.com/issues/18126
Revert this when it is fixed.
=> do all valgrind runs on centos

tasks/ceph.py
Default to xfs instead of using root fs dir
for osd
=> tasks/ceph: default to xfs instead of root dir

tasks/ceph.py
The current loop can cause the logs to run into huge file and loop forever in case of dead monitors, This change will cause it exit after 10minutes if they dont reach quorum.
=> Fix infinite wait during monitor quorum check

suites/rgw/singleton/all/radosgw-admin-data-sync.yaml, suites/rgw/singleton/all/radosgw-admin.yaml
http://tracker.ceph.com/issues/15612
Not all test machines(mira, vps) have 4 osd's and without this
change it will fail on nodes with < 4 osds, since one of the
osd will be on ext4 and it will hit long filename issue
=> rgw: split osd's in 2 nodes

suites/rgw/verify/overrides.yaml, tasks/rgw.py
~~This is my naive attempt to add `rgw_compression_type={none, snappy, zlib}` to the test matrix of the rgw suite to validate https://github.com/ceph/ceph/pull/7715. I would eventually like to narrow down which parts of the rgw suite test with compression.. maybe just running s3tests against each type is good enough.~~
This uses the new compressor plugin factory's support for the compression type "random" (see https://github.com/ceph/ceph/pull/11901) to get test coverage of all supported compression types without expanding the test matrix of the rgw suite.
=> rgw/verify: use rgw_compression_type = "random"

suites/fs/multiclient/tasks/fsx-mpi.yaml.disabled
added missing -o option to mpi exec.
added gmnt file reference to mpi exec.
run fsx-mpi as sudo.
run chef task so that libmpich2-dev gets installed (fsx-mpi.c uses it).
Signed-off-by: Warren Usui warren.usui@inktank.com
Fixes: #1398
=> Fix mpi calls

tasks/ceph.py
all newly created files and directories under the mount dir inherit the
SELinux type of their parent directory. so we need to set it before
mkfs.
Fixes: http://tracker.ceph.com/issues/16800
=> tasks/ceph: restore context of osd mount path before mkfs
