- tasks/__init__.py
Signed-off-by: Zack Cerza <zack@redhat.com>
> Inherit teuthology's log level

- suites/upgrade/firefly/newer/0-cluster/start.yaml
- suites/upgrade/firefly/older/0-cluster/start.yaml
@liewegas Pls review and merge
> Fixes http://tracker.ceph.com/issues/10525

- tasks/calamari_setup.py
Signed-off-by: Warren Usui <warren.usui@inktank.com>
Fixes: #10261
> Calamari_setup now allows > 1 mon.

- tasks/ceph_manager.py
- tasks/repair_test.py
Reverts ceph/ceph-qa-suite#250
> Revert "add erasure code repair / scrub tests"

- suites/upgrade/firefly/singleton/versions-steps-x/versions-steps-x.yaml
- suites/upgrade/firefly/singleton/versions-steps/versions-steps.yaml
> Replaced step for v0.80.6 with v0.80.7

- suites/upgrade/firefly/singleton/versions-steps-x/versions-steps-x.yaml
- suites/upgrade/firefly/singleton/versions-steps/versions-steps.yaml
> Changed to "osd map max advance: 1000"

- tasks/calamari_setup.py
A few bug fixes/enhancements to calamari-setup
> Tweaks to calamari-setup

- suites/upgrade/firefly/newer/1-install/v0.80.8.yaml
- suites/upgrade/firefly/older/5-final/testrgw.yaml
- suites/upgrade/firefly/singleton/versions-steps-x/versions-steps-x.yaml
- suites/upgrade/firefly/singleton/versions-steps/versions-steps.yaml
@tmuthamizhan 
@liewegas 
Re: http://tracker.ceph.com/issues/10538
Pls review
Signed-off-by: Yuri Weinstein yuri.weinstein@inktank.com
> Add v0.80.8 to firefly stable suites (issue 10538)

- suites/rgw/singleton/all/radosgw-convert-to-region.yaml
- tasks/radosgw_admin.py
A couple of fixes to the suite to issues that turned up on the bucket sharding branch but also affect current master.
> Wip bi sharding 3

- suites/upgrade/dumpling/rgw/2-workload/testrgw.yaml
@yehudasa 
@dachary 
Pls review and merge.
Signed-off-by: Yuri Weinstein <yuriw@magna002.ceph.redhat.com>
> Fixes http://tracker.ceph.com/issues/10593

- suites/upgrade/dumpling/rgw/2-workload/testrgw.yaml
Reverts ceph/ceph-qa-suite#305
> Revert "Fixes http://tracker.ceph.com/issues/10593"

- tasks/s3tests.py
@dachary 
@yehudasa 
@zmc 
Signed-off-by: Zack Cerza <zack.cerza@inktank.com>
(cherry picked from commit 1b8d31986a5a8bc4cd9fea90eb680db3ca1866c8)
Conflicts:
tasks/s3tests.py
Fixes http://tracker.ceph.com/issues/10593
> Smarter s3tests branch selection

- tasks/ceph_manager.py
***** This must wait for merge of pull request 3246 in ceph repo.
> DNM: ceph-objectstore-tool import/export and related fixes

- tasks/mds_flush.py
[Depends on Ceph PR https://github.com/ceph/ceph/pull/3402]
Where previously we only tracked RADOS-level delete
ops during deletion, now also verify that they
correspond to the right number of MDS-level purge
operations.
> tasks/mds_flush: use new stray/purge perfcounters

- suites/upgrade/dumpling-firefly-x/stress-split/09-workload/rbd-python.yaml
> Added "branch: dumpling" to fix #10577

- suites/rados/thrash/workloads/cache-agent-small.yaml
- suites/rados/thrash/workloads/rados_api_tests.yaml
- suites/rados/thrash/workloads/readwrite.yaml
- suites/rados/thrash/workloads/small-objects.yaml
- tasks/ceph.py
Like so:
overrides:
ceph:
crush_tunables: hammer
> ceph: set crush tunables

- suites/rados/thrash/workloads/write_fadvise_dontneed.yaml
- tasks/rados.py
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>
> rados.py: Add write_fadvise_dontneed field

- suites/multi-version/dumpling-x/basic/2-workload/rbd_cls.yaml
- suites/multi-version/firefly-x/basic/2-workload/rbd_cli_import_export.yaml
@jdurgin did I understand you correctly on this issue?  pls review
> Fixes http://tracker.ceph.com/issues/10652

- suites/rados/singleton/msgr-failures/msgr.yaml
Should wait for https://github.com/ceph/ceph/pull/3423 merged.
Signed-off-by: Haomai Wang <haomaiwang@gmail.com>
> rados: include msgr tests

- tasks/calamari_setup.py
Add an extra '\n' to the interaction string to answer it
> tasks/calamari_setup: ice_setup 0.2.0 has added another prompt

- suites/multi-version/firefly-x/basic/2-workload/rbd_cli_import_export.yaml
> Corrected "branch" to be outside of the 'clients:' section

- suites/rbd/librbd/workloads/qemu_bonnie.yaml
- suites/rbd/librbd/workloads/qemu_fsstress.yaml
- suites/rbd/librbd/workloads/qemu_iozone.yaml.disabled
- suites/rbd/librbd/workloads/qemu_xfstests.yaml
> always wget from the ceph dumpling branch

- tasks/cephfs/fuse_mount.py
This was broken in the case of multiple
mounts, and in the case of stuck mounts.
Fixes: #10702
> tasks/cephfs: fix fuse force unmount

- .gitignore
- suites/teuthology/ceph/tasks/teuthology.yaml
Also, I added some things to .gitignore.  pycs and __pycache__ folders showed up after running the tests in task/tests
> Make jobs in the teuthology suite that install ceph run the 'tests' task

- tasks/ceph.py
this is trying to track down why we keep seeing that umount hting all the
time!
> lsof on umount failure; catpure logs for aggressively

- suites/upgrade/giant-x/parallel/0-cluster/start.yaml
- suites/upgrade/giant-x/parallel/2-workload/ec-rados-default.yaml
- suites/upgrade/giant-x/parallel/2-workload/parallel_run/ec-rados-parallel.yaml
- suites/upgrade/giant-x/parallel/2-workload/parallel_run/rados_api.yaml
- suites/upgrade/giant-x/parallel/2-workload/parallel_run/rados_loadgenbig.yaml
- suites/upgrade/giant-x/parallel/2-workload/parallel_run/test_cache-pool-snaps.yaml
- suites/upgrade/giant-x/parallel/2-workload/parallel_run/test_rbd_api.yaml
- suites/upgrade/giant-x/parallel/2-workload/parallel_run/test_rbd_python.yaml
- suites/upgrade/giant-x/parallel/2-workload/sequential_run/ec-rados-default.yaml
- suites/upgrade/giant-x/parallel/2-workload/sequential_run/rados_api.yaml
- suites/upgrade/giant-x/parallel/2-workload/sequential_run/rados_loadgenbig.yaml
- suites/upgrade/giant-x/parallel/2-workload/sequential_run/test_cache-pool-snaps.yaml
- suites/upgrade/giant-x/parallel/2-workload/sequential_run/test_rbd_api.yaml
- suites/upgrade/giant-x/parallel/2-workload/sequential_run/test_rbd_python.yaml
FYI and review
@liewegas @tmuthamizhan @wusui @jdurgin 
This is new tests similar we have in firefly-x but implemented for giant-x
Signed-off-by: Yuri Weinstein yuri.weinstein@inktank.com
> Wip 10704 (FEATURE #10704)

- suites/rados/thrash/workloads/cache-pool-snaps-readproxy.yaml
> rados/thrash: add readproxy facet

- tasks/ceph.py
- tasks/ceph_deploy.py
- tox.ini
This fixes one issue that I was unable to cherry-pick from master.
Reference issue: http://tracker.ceph.com/issues/10954
> linter fixes for firefly

- .gitignore
- tasks/ceph_deploy.py
- tasks/ceph_fuse.py
- tasks/cephfs/mount.py
- tasks/repair_test.py
A few cherry picks are included as well. Some other cherry picks were pushed already.
Reference issue: http://tracker.ceph.com/issues/10954
> lint fixes for hammer

- tasks/ceph.py
- tasks/ceph_deploy.py
- tasks/ceph_manager.py
- tasks/omapbench.py
- tasks/radosbench.py
- tasks/radosgw_admin.py
- tasks/rest_api.py
- tasks/rgw.py
- tasks/util/rgw.py
- tasks/watch_notify_stress.py
That I wasn't able to cherry-pick from master.
Reference issue: http://tracker.ceph.com/issues/10954
> lint fixes for dumpling

- suites/rbd/singleton/all/formatted-output.yaml
> pull cram tests from the firelfy branch

- tasks/cephfs/fuse_mount.py
teuthology helpfully escapes things for us so
the \; didn't need the backslash.  The logic
was still falling over in some cases too.
> tasks/cephfs: fix fuse force umount (again)

- tasks/mds_flush.py
This was an overly strict success condition: the
flush operation doesn't promise to leave you an empty
journal, it promises that anything in the journal
before the flush will be flushed.
Fixes: #10712
> tasks: fix intermittent failure in TestFlush

- tasks/cephfs/filesystem.py
Where multiple MDSs were on the same node, trying
to concurrently update their firewall state was
causing an exception because the iptables command
errors out if another instance is already running.
Fixes: #10948
> tasks/cephfs: don't run iptables in parallel

- tasks/qemu.py
> Control the nfs service correctly on rpm-based systems

- tasks/mds_journal_repair.py
To avoid internal.coredump task synthesizing a failure
during teardown from the core we left behind.
Fixes: #10949
> tasks/cephfs: clean up core on deliberate crash

- suites/hadoop/basic/tasks/repl.yaml
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
(cherry picked from commit 6a348ae1870eb4e22a35f4ea86d897fb6d960b88)
> hadoop: fixup for new replication test

- suites/upgrade/client-upgrade/firefly-x/basic/1-install/firefly-x.yaml
- suites/upgrade/client-upgrade/firefly-x/basic/2-workload/rbd_cli_import_export.yaml
@jdurgin Pls review
I did only for firefly-x test as dumpling-x was passing, but maybe we should do for it as well?
Here is the latest run - http://pulpito.front.sepia.ceph.com/teuthology-2015-03-04_23:20:02-upgrade:client-upgrade-master-distro-basic-multi/
> Implemented "exclude_packages" feature #11043

- suites/upgrade/firefly/newer/1-install/v0.80.9.yaml
- suites/upgrade/firefly/singleton/versions-steps-x/versions-steps-x.yaml
- suites/upgrade/firefly/singleton/versions-steps/versions-steps.yaml
> Added v0.80.9 to upgrade/firefly suite, fixed #11072

- suites/rados/objectstore/ceph_objectstore_tool.yaml
- tasks/ceph.py
- tasks/ceph_manager.py
- tasks/ceph_objectstore_tool.py
- tasks/thrashosds.py
Tests ceph/ceph#3866.  They should be merge together.
> Backport ceph-objectstore-tool changes to firefly  

- tasks/radosgw_admin.py
Reference issue: http://tracker.ceph.com/issues/11180
> ensure summary is looked for the user we need

- tasks/calamari_setup.py
Started by @GregMeno, finished by me
> Add support for ISOs to tasks/calamari_setup

- tasks/radosgw_admin.py
- tasks/radosgw_admin_rest.py
- tasks/util/rgw.py
http://tracker.ceph.com/issues/11180 Fixes: #11180
> ensure summary is looked for the user we need (part 2)

- suites/upgrade/firefly-x/stress-split/0-cluster/start.yaml
@jdurgin 
@gregsfortytwo 
Pls review
> Fixes #11166, whitelisted 'Missing health data for MDS'

- tasks/calamari_setup.py
> calamari_setup: der.  Use dict.update() correctly

- tasks/ceph_manager.py
Fixes: #11204
Signed-off-by: David Zafman <dzafman@redhat.com>
> Make sure that ulimits are adjusted for ceph-objectstore-tool

- suites/rados/thrash-erasure-code/thrashers/default.yaml
- suites/rados/thrash-erasure-code/thrashers/mapgap.yaml
- suites/rados/thrash-erasure-code/thrashers/morepggrow.yaml
- suites/rados/thrash-erasure-code/thrashers/pggrow.yaml
- suites/rados/thrash/thrashers/default.yaml
- suites/rados/thrash/thrashers/mapgap.yaml
- suites/rados/thrash/thrashers/morepggrow.yaml
- suites/rados/thrash/thrashers/pggrow.yaml
> rados/thrash*: make scrubs happen a lot

- suites/rados/basic/tasks/repair_test.yaml
- suites/rados/basic/tasks/scrub_test.yaml
> (scrub|rados)_test: tolerate best guess digest errors as well

- suites/rados/basic/tasks/rados_python.yaml
> rados_python: whitelist wrongly marked me down

- suites/upgrade/client-upgrade/dumpling-x/basic/0-cluster/start.yaml
- suites/upgrade/client-upgrade/firefly-x/basic/0-cluster/start.yaml
- suites/upgrade/dumpling-firefly-x/parallel/0-cluster/start.yaml
- suites/upgrade/dumpling-firefly-x/stress-split/00-cluster/start.yaml
- suites/upgrade/dumpling-x/parallel/0-cluster/start.yaml
- suites/upgrade/dumpling-x/stress-split/0-cluster/start.yaml
- suites/upgrade/firefly-x/parallel/0-cluster/start.yaml
- suites/upgrade/firefly-x/stress-split/0-cluster/start.yaml
- suites/upgrade/giant-x/parallel/0-cluster/start.yaml
- suites/upgrade/giant-x/stress-split/0-cluster/start.yaml
@athanatos Pls review and merge
> Fixed #11306 Whitelist WRN "failed to encode map"

- tasks/ceph.py
We'll come back later and provide a better solution to this.
See: http://tracker.ceph.com/issues/11308
Reverts ceph/ceph-qa-suite#385
> Revert "ceph: be less weird about passing -f to mkfs"

- tasks/radosgw_agent.py
- tasks/restart.py
- tasks/workunit.py
> git.ceph.com

- suites/rbd/qemu/workloads/qemu_bonnie.yaml
- suites/rbd/qemu/workloads/qemu_fsstress.yaml
- suites/rbd/qemu/workloads/qemu_iozone.yaml.disabled
- suites/rbd/qemu/workloads/qemu_xfstests.yaml
- suites/rbd/singleton/all/formatted-output.yaml
- tasks/chef.py
- tasks/filestore_idempotent.py
- tasks/radosgw_agent.py
> git.ceph.com (hammer)

- suites/rbd/librbd/workloads/qemu_bonnie.yaml
- suites/rbd/librbd/workloads/qemu_fsstress.yaml
- suites/rbd/librbd/workloads/qemu_iozone.yaml.disabled
- suites/rbd/librbd/workloads/qemu_xfstests.yaml
- suites/rbd/singleton/all/formatted-output.yaml
- tasks/chef.py
- tasks/filestore_idempotent.py
- tasks/radosgw_agent.py
> git.ceph.com (firefly)

- tasks/ceph.py
- tasks/ceph_deploy.py
- tasks/cephfs/filesystem.py
- tasks/mds_journal_repair.py
Created at Yuri's request -- although this is weird, usually if a next branch is in play we would fix something there and then merge to master, rather than backporting from next.
> Backport to next: fix ceph-deploy task with CephFS (#11316)

- suites/fs/recovery/tasks/client-limits.yaml
- tasks/cephfs/test_client_limits.py
> cephfs/test_client_limits.py: test for client oldest tid warning

- suites/upgrade/hammer/0-cluster/start.yaml
- suites/upgrade/hammer/1-install/latest_giant_release.yaml
- suites/upgrade/hammer/2-workload/blogbench.yaml
- suites/upgrade/hammer/2-workload/rbd.yaml
- suites/upgrade/hammer/2-workload/s3tests.yaml
- suites/upgrade/hammer/2-workload/testrados.yaml
- suites/upgrade/hammer/3-upgrade-sequence/upgrade-mon-osd-mds.yaml
- suites/upgrade/hammer/3-upgrade-sequence/upgrade-osd-mon-mds.yaml
- suites/upgrade/hammer/4-final/monthrash.yaml
- suites/upgrade/hammer/4-final/osdthrash.yaml
- suites/upgrade/hammer/4-final/testrgw.yaml
- suites/upgrade/hammer/distros
@liewegas 
@tmuthamizhan 
@jdurgin 
FYI
> Initial check in for upgrades/hammer stable upgrade suite

- suites/rados/singleton-nomsgr/all/11429.yaml
- tasks/ceph.py
- tasks/ceph_manager.py
- tasks/rados.py
- tasks/radosbench.py
- tasks/utility.py
http://tracker.ceph.com/issues/11429
> suites/rados: add test for 11429 (firefly)

- suites/fs/recovery/tasks/mds-full.yaml
- tasks/cephfs/filesystem.py
- tasks/cephfs/test_full.py
DNM because waiting for
* https://github.com/ceph/ceph/pull/4226
* https://github.com/ceph/ceph-qa-suite/pull/383
> Test for CephFS full handling with pool quotas (#11276)

- tasks/cephfs/mount.py
- tasks/cephfs/test_client_recovery.py
flock only works properly on FUSE versions >=2.9, which is newer
than eg Ubuntu Precise. So check the version on our client mounts and
only test flock if it's at least that new.
> cephfs/mount: check FUSE version before invoking flock

- tasks/cephfs/test_full.py
The interval between writes was too short because
it was not taking account of the way OSDMap full
flags are set on tick rather than immediately.
Fixes: #11779
> tasks/cephfs: fix timing in test_full

- tasks/cephfs/test_full.py
Sometimes mount A would get a cap revoke when mount
B did its last IO, resulting in mount A's OSD epoch
getting updated too.
Fix by making sure mount B is the last one to have
done IO before we do the barrier, so that when
it does IO again after the barrier, mount A can't
be holding any caps that B would need.
Fixes: #11913
> tasks/cephfs: fix race in test_full

- tasks/ceph.py
> ceph: fix up log rotation stopper

- suites/upgrade/firefly/newer/1-install/v0.80.10.yaml
> Added firefly v0.80.10 to the mix

- suites/upgrade/hammer/basic/2-workload/rbd.yaml
Removed as the hammer tests with new feature runs against giant osd's
@jdurgin Pls review and merge
> Wip remove test_cls_rbd

- tasks/calamari_setup.py
Fixes #12185
Signed-off-by: Warren Usui <warren.usui@inktank.com>
> tasks/calamari_setup.py cal_svr.run arg list is missing args keyword.

- tasks/calamari_nosetests.py
> calamari_nosetests: verify that calamari_branch exists

- tasks/cephfs/fuse_mount.py
hammer backport to fix failure seen:
http://pulpito.ceph.redhat.com/teuthology-2015-07-04_18:14:02-samba-hammer---basic-magna/
teuthology helpfully escapes things for us so
the \; didn't need the backslash.  The logic
was still falling over in some cases too.
Additionally, make the FUSE /sys/ abort operation
more surgical by working out the connection name
of our own mount during mount().
(cherry picked from commit fc4e90930b2c6ba0d395ae7d6edb8f8daba3fd64)
> tasks/cephfs: fix/improve fuse force umount (again)

- suites/fs/recovery/tasks/damage.yaml
- tasks/cephfs/filesystem.py
- tasks/cephfs/mount.py
- tasks/cephfs/test_damage.py
This stuff is also in wip-offline-backward but separated out here.
DNM until wip-damaged-fixes in ceph tree
> Tests for wip-damaged-fixes

- suites/fs/recovery/tasks/backtrace.yaml
- tasks/cephfs/filesystem.py
- tasks/cephfs/test_backtrace.py
> Add cephfs TestBacktrace

- tasks/calamari_setup.py
Also, clean up the command handling; failure will throw an exception,
so no need to accumulate the errors in an int
Fixes: #12228
> calamari_setup: handle new structure in 1.3.0 (MON and OSD repos)

- suites/rbd/qemu/cachepool/ec-cache.yaml
> suites/rbd: add EC pool variant for QEMU tests

- suites/upgrade/firefly/newer/2-workload/s3tests.yaml
- suites/upgrade/firefly/older/5-final/testrgw.yaml
- suites/upgrade/firefly/singleton/upgrade_client/upgrade_client_first.yaml
- suites/upgrade/firefly/singleton/versions-steps-x/versions-steps-x.yaml
- suites/upgrade/firefly/singleton/versions-steps/versions-steps.yaml
same as in https://github.com/ceph/ceph-qa-suite/pull/494
@dmick @jdurgin FYI
> Changed 'firefly-original' ref to 'firefly'

- suites/upgrade/firefly-x/parallel/0-cluster/start.yaml
- suites/upgrade/giant-x/parallel/0-cluster/start.yaml
- suites/upgrade/hammer/point-to-point/point-to-point.yaml
("mon debug unsafe allow tier with nonempty snaps: true")
@athanatos Ple review and merge
> Added config settings to resolve and test #12021

- suites/upgrade/firefly/newer/2-workload/s3tests.yaml
- suites/upgrade/firefly/older/5-final/testrgw.yaml
See https://github.com/ceph/ceph-qa-suite/pull/495/
@jdurgin Pls review and merge
> Partly reverted ref to firefly-orginal

- tasks/calamari_setup.py
ceph-deploy enables EPEL on Centos; this caused problems for
Calamari.  Undo it after ceph-deploy has installed Ceph.
> calamari_setup: disable epel again after ceph-deploy

- suites/upgrade/hammer-x/point-to-point-x/distros
- suites/upgrade/hammer-x/point-to-point-x/point-to-point.yaml
point-to-point test moved from upgrade/hammer and modified to run as -x type upgrade
See http://tracker.ceph.com/issues/12068
@athanatos Pls review and merge
@tmuthamizhan @liewegas FYI
> Fixes #12068

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
@athanatos @liewegas pls review and merge
> Fixes #12460

- suites/krbd/unmap/ceph/ceph.yaml
- suites/krbd/unmap/clusters/fixed-1.yaml
- suites/krbd/unmap/kernels/pre-single-major.yaml
- suites/krbd/unmap/kernels/single-major-off.yaml
- suites/krbd/unmap/kernels/single-major-on.yaml
- suites/krbd/unmap/tasks/unmap.yaml
- tasks/ceph_deploy.py
Depends on https://github.com/ceph/teuthology/pull/500.
> unmap subsuite for krbd

- tasks/ceph_manager.py
- tasks/thrashosds.py
See: http://tracker.ceph.com/issues/12476
> thrashosds: send a random osd a signal.SIGHUP

- tasks/ceph.py
This is for http://tracker.ceph.com/issues/12621
> Set the SELinux context of the logrotate config

- tasks/calamari_setup.py
> calamari_setup: change to use ceph-deploy repo command

- suites/rados/upgrade/hammer-x-singleton/0-cluster/start.yaml
- suites/rados/upgrade/hammer-x-singleton/1-hammer-install/hammer.yaml
- suites/rados/upgrade/hammer-x-singleton/2-partial-upgrade/firsthalf.yaml
- suites/rados/upgrade/hammer-x-singleton/3-thrash/default.yaml
- suites/rados/upgrade/hammer-x-singleton/4-mon/mona.yaml
- suites/rados/upgrade/hammer-x-singleton/5-workload/rbd-cls.yaml
- suites/rados/upgrade/hammer-x-singleton/5-workload/rbd-import-export.yaml
- suites/rados/upgrade/hammer-x-singleton/5-workload/readwrite.yaml
- suites/rados/upgrade/hammer-x-singleton/5-workload/snaps-few-objects.yaml
- suites/rados/upgrade/hammer-x-singleton/6-next-mon/monb.yaml
- suites/rados/upgrade/hammer-x-singleton/7-workload/radosbench.yaml
- suites/rados/upgrade/hammer-x-singleton/7-workload/rbd_api.yaml
- suites/rados/upgrade/hammer-x-singleton/8-next-mon/monc.yaml
- suites/rados/upgrade/hammer-x-singleton/9-workload/ec-rados-plugin=jerasure-k=3-m=1.yaml
- suites/rados/upgrade/hammer-x-singleton/9-workload/rbd-python.yaml
- suites/rados/upgrade/hammer-x-singleton/9-workload/rgw-swift.yaml
- suites/rados/upgrade/hammer-x-singleton/9-workload/snaps-many-objects.yaml
- suites/rados/upgrade/hammer-x-singleton/9-workload/test_cache-pool-snaps.yaml
@athanatos @liewegas - does this address what we discussed, e.g running simplified one-off hammer-x test during master branch  nightlies runs?
> Added singleton hammer-x test to address #12625

- suites/kcephfs/cephfs/conf.yaml
> tasks/kcephfs: enable MDS debug

- distros/supported/centos_6.5.yaml
- distros/supported/centos_7.0.yaml
- distros/supported/ubuntu_12.04.yaml
- suites/ceph-deploy/basic/tasks/ceph-deploy_hello_world.yaml
> ceph-deploy: hints for OpenStack

- tasks/cephfs/mount.py
- tasks/cephfs/test_data_scan.py
This is for testing how cephfs-data-scan handles
the new 'layout' xattr when found during recovery.
> tasks/cephfs: implement TestDataScan.test_stashed_layout

- suites/upgrade/firefly-x/singleton/versions-steps-x/versions-steps-x.yaml
@gregsfortytwo @ukernel Pls review and merge
> Whitelisted "bad backtrace on dir ino" to fis #12715

- suites/rados/thrash/hobj-sort.yaml
> suites/rados/thrash: randomize hobject sort order

- suites/rados/basic/msgr/async.yaml
- suites/rados/basic/msgr/random.yaml
- suites/rados/basic/msgr/simple.yaml
- suites/rados/monthrash/msgr
- suites/rados/multimon/msgr
- suites/rados/singleton/msgr
- suites/rados/thrash/msgr
- suites/rados/verify/msgr
- in general, test simple vs async vs random
- not for msgr-less workloads
- not for thrash-erasure-*.. the regular thrash
should cover it.
> rados: test both simple, async, and a mix

- tasks/cephfs/test_pool_perm.py
> tasks/cephfs: fix test_pool_perm teardown

- suites/rados/basic/msgr/async.yaml
- suites/rados/basic/msgr/random.yaml
> rados/basic/msgr: enable all experimental features if random/async

- suites/ceph-disk/basic/distros
- suites/ceph-disk/basic/options/ceph-conf.yaml
- suites/ceph-disk/basic/tasks/ceph-disk.yaml
- tasks/ceph_deploy.py
To run the ceph-disk workunit http://tracker.ceph.com/issues/11881
> ceph-disk workunit

- erasure-code/ec-rados-plugin=lrc-k=4-m=2-l=3.yaml
- suites/rados/thrash-erasure-code-big/cluster/12-osds.yaml
- suites/rados/thrash-erasure-code-big/fs
- suites/rados/thrash-erasure-code-big/msgr-failures
- suites/rados/thrash-erasure-code-big/thrashers/default.yaml
- suites/rados/thrash-erasure-code-big/thrashers/fastread.yaml
- suites/rados/thrash-erasure-code-big/thrashers/mapgap.yaml
- suites/rados/thrash-erasure-code-big/thrashers/morepggrow.yaml
- suites/rados/thrash-erasure-code-big/thrashers/pggrow.yaml
- suites/rados/thrash-erasure-code-big/workloads/ec-rados-plugin=lrc-k=4-m=2-l=3.yaml
- suites/rados/thrash-erasure-code/thrashers/fastread.yaml
https://github.com/ceph/ceph-qa-suite/pull/445
https://github.com/ceph/ceph-qa-suite/pull/499
Signed-off-by: Guang Yang <yguang@yahoo-inc.com>
> erasure coding: LRC thrasher & fast read thrasher

- tasks/radosbench.py
> tasks/radosbench: allow cleanup: false

- suites/rados/singleton-nomsgr/all/11429.yaml
This verifies the fix for 13060 and also the similar fix for infernalis.
> fix test for 11429 (and now 13060)

- suites/teuthology/buildpackages/buildpackages.yaml
- tasks/buildpackages.py
- tasks/buildpackages/Makefile
- tasks/buildpackages/make-debs.sh
this is not used anywhere yet. I committed this two days ago by mistake it seems, while I was trying to push changes to the wip-13031-packages branch from the main repository because it's needed to test changes. I'll be more careful in the future.
> buildpackages: fix flake / pep8

- suites/teuthology/buildpackages/distros
- suites/teuthology/buildpackages/tasks/builpackages.yaml
- suites/teuthology/buildpackages/ubuntu_14.04.yaml
- tasks/buildpackages.py
- tasks/buildpackages/Makefile
- tasks/buildpackages/common.sh
- tasks/buildpackages/make-deb.sh
- tasks/buildpackages/make-rpm.sh
- tasks/buildpackages/user-data.txt
> buildpackages: make rpm packages

- tasks/ceph_manager.py
This races with pool deletion sometimes.
I know I should catch the exeption by name but I'm not sure how to tell
what it is named...
> tolerate pg_num get failure

- suites/rados/singleton-nomsgr/all/full-tiering.yaml
> rados/singleton-nomsgr/all/full-tiering: test full cache tier

- tasks/cephfs/cephfs_test_case.py
- tasks/cephfs/test_pool_perm.py
> tasks/cephfs: mds allow

- suites/rados/singleton-nomsgr/all/13234.yaml
- tasks/ceph_manager.py
> rados: add test for 13234.yaml

- tasks/cephfs/test_client_limits.py
merge this after https://github.com/ceph/ceph/pull/4791
> cephfs/test_client_limits.py: update test_client_oldest_tid

- suites/upgrade/hammer-x/point-to-point-x/point-to-point.yaml
@liewegas fyi and testing this now
This http://pulpito.ceph.com/teuthology-2015-10-03_08:31:28-upgrade:hammer-x:point-to-point-x-infernalis-distro-basic-vps/ passed, 
pls merge
> White listed WAR 'failed to encode' fixes #13349

- suites/smoke/basic/tasks/rgw_ec_s3tests.yaml
Add s3tests using ec data pool
> s3tests using ec data pool for smoke

- suites/upgrade/giant-x/stress-split-erasure-code-x86_64/distros/rhel_7.0.yaml
@dachary @zmc pls review and merge
> Removed rhel distro, fixes #13393 as rhel is not supported in sepia lab

- suites/upgrade/firefly-hammer-x/parallel/7-final-workload/rados_mon_thrash.yaml
> Specified 'firefly' branch

- tasks/buildpackages.py
- tasks/buildpackages/Makefile
- tasks/buildpackages/common.sh
- tasks/buildpackages/make-deb.sh
- tasks/buildpackages/make-rpm.sh
http://tracker.ceph.com/issues/13454 Fixes: #13454
> buildpackages: implement notcmalloc flavor

- distros/supported/centos_6.5.yaml
> Removed centos 6.5 from config, fixes #13366

- tasks/rbd_fio.py
http://tracker.ceph.com/issues/13431
use cephtest as base dir during testing and in case of failures let nuke cleanup any stale dir's
> use cephtest as base dir during testing 

- suites/upgrade/firefly-hammer-x/stress-split/05-workload/readwrite.yaml
@liewegas pls review and merge 
> Added write_append_excl: false to fix #13485

- suites/upgrade/firefly-hammer-x/stress-split/17-workload/readwrite.yaml
> Added "write_append_excl: false"

- suites/upgrade/firefly-hammer-x/stress-split/11-workload/snaps-few-objects.yaml
@liewegas 
Passed with the change here  http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2015-10-17_15:30:18-upgrade:firefly-hammer-x:stress-split-infernalis-distro-basic-openstack/
> Added one more "write_append_excl: false"

- suites/upgrade/hammer/newer/1-install/v0.94.4.yaml
@tmuthamizhan @liewegas 
Pls review, also consider if we can remove v0.94.2 from the mix
> Added v0.94.4 to the mix

- suites/fs/32bits/dirfrag/frag_enable.yaml
- suites/fs/basic/dirfrag/frag_enable.yaml
> fs: fix two frag_enable fragments

- tasks/samba.py
A few fixes to our handling of smbd to prevent spurious exit code failures.
> Firefly samba fixes

- machine_types/schedule_rados.sh
> Added $4 for filter out "random.yaml\,async.yaml" tests for now

- suites/rados/basic/msgr/async.yaml
- suites/rados/basic/msgr/random.yaml
> basic/msgr: remove async and random for now

- tasks/cephfs/test_auto_repair.py
This was previously using a bunch of files and a small
MDCache limit to force things out of cache.  It is much
simpler to just drop the journal.
> tasks/cephfs: simplify test_backtrace_repair

- suites/rados/singleton-nomsgr/all/export-after-evict.yaml
add a test for http://tracker.ceph.com/issues/12748
Fixes: #12748
> rados/singleton-nomsgr/all: add export-after-evict.yaml

- suites/rbd/qemu/workloads/qemu_bonnie.yaml
- suites/rbd/qemu/workloads/qemu_fsstress.yaml
- suites/rbd/qemu/workloads/qemu_xfstests.yaml
- tasks/qemu.py
- tasks/rbd.py
> suites/rbd/qemu: excercise CoW support during QEMU testing

- tasks/buildpackages/Makefile
> buildpackages: silently ignore IPv6 addresses

- tasks/workunit.py
This should fix http://tracker.ceph.com/issues/13658 along with several other issues.
> tasks/workunit: Apply several fixes from master

- suites/krbd/rbd/tasks/rbd_fio.yaml
- suites/krbd/thrash/workloads/rbd_fio.yaml
- suites/rbd/librbd/workloads/rbd_fio.yaml
- tasks/rbd_fio.py
> rbd_fio: removed deprecated command-line option to rbd CLI

- suites/krbd/rbd/tasks/rbd_fio.yaml
- suites/krbd/thrash/workloads/rbd_fio.yaml
- suites/rbd/librbd/workloads/rbd_fio.yaml
- tasks/rbd_fio.py
fio overison 2.2.11 has fix for tracker issue 13432
> Update fio version from 2.2.9 to 2.2.11

- machine_types/schedule_rados.sh
@liewegas @athanatos 
Hope /28 will reduce ~50% of jobs
> Reducing the ammount of resulting jobs scheduled

- suites/upgrade/hammer-x/f-h-x-offline/0-install.yaml
- suites/upgrade/hammer-x/f-h-x-offline/2-upgrade.yaml
Fixed intall.upgrade syntax
Whitelisted 'reached quota'
> Fixing /hammer-x/f-h-x-offline suite

- tasks/buildpackages.py
> buildpackages: 10GB is too small most of the time

- tasks/buildpackages/make-rpm.sh
And there really is nothing we can do about it expect ignore them.
> buildpackages: giant has some unpackaged files

- machine_types/schedule_rados.sh
> Require -e arg for email address

- tasks/buildpackages/Makefile
> buildpackages: protect packages-repository

- suites/upgrade/infernalis/point-to-point/point-to-point.yaml
- suites/upgrade/infernalis/point-to-point/ubuntu_14.04.yaml
More tests to be added later
@liewegas @jdurgin @dachary 
Pls review
> Added infernalis point-to-point as inital draft for 'stable' upgrades

- suites/upgrade/client-upgrade/infernalis-client-x/basic/0-cluster/start.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/basic/1-install/infernalis-client-x.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/basic/2-workload/rbd_api_tests.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/basic/2-workload/rbd_cli_import_export.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/rbd/0-cluster/start.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/rbd/1-install/infernalis-client-x.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/rbd/2-workload/rbd_notification_tests.yaml
@dillaman 
@jdurgin 
This will run on jewel branch only
> Added infernalis-client-x

- tasks/buildpackages/common.sh
- tasks/buildpackages/make-deb.sh
- tasks/buildpackages/make-rpm.sh
http://tracker.ceph.com/issues/13845 Refs: #13845
> buildpackages: do not -jX on dumpling

- suites/ceph-deploy/basic/tasks/ceph-deploy_hello_world.yaml
- suites/rados/objectstore/alloc-hint.yaml
- suites/rados/singleton-nomsgr/all/msgr.yaml
- suites/rados/thrash/clusters/openstack.yaml
- suites/smoke/1node/clusters/openstack.yaml
So that it is more flexible.
http://tracker.ceph.com/issues/13581 Fixes: #13581
> openstack: convert to array hints

- suites/rbd/qemu/clusters/openstack.yaml
- suites/rbd/thrash/clusters/openstack.yaml
http://tracker.ceph.com/issues/13856
http://tracker.ceph.com/issues/13270
> openstack: rbd/thrash and rbd/qemu resources

- suites/rados/thrash-erasure-code/workloads/ec-small-objects-fast-read.yaml
- tasks/rados.py
> rados: add test for ec fast_read

- tasks/cephfs/test_journal_repair.py
> tasks/cephfs: include an empty dir in journal repair

- tasks/cephfs/test_sessionmap.py
> tasks/cephfs: fix race in test_sessionmap

- suites/rados/thrash/thrashers/morepggrow.yaml
> openstack: rados/.../morepggrow.yaml may need more disk

- tasks/ceph.py
Backport of https://github.com/ceph/ceph-qa-suite/pull/679
...because otherwise it lights up like a christmas
tree in pycharm.
(cherry picked from commit f05d9776281d27df03e74e10085e691669532e95)
> tasks/ceph: fix up whitespace

- suites/teuthology/integration.yaml
- tasks/teuthology_integration.py
> teuthology-integration: run teuthology integration tests

- suites/fs/recovery/tasks/data-scan.yaml
> suites: yaml for TestDataScan

- suites/upgrade/hammer/older/2-workload/blogbench.yaml
> Fixed missing ceph-fuse

- suites/fs/recovery/tasks/forward-scrub.yaml
- tasks/cephfs/mount.py
- tasks/cephfs/test_auto_repair.py
- tasks/cephfs/test_client_recovery.py
- tasks/cephfs/test_data_scan.py
- tasks/cephfs/test_forward_scrub.py
- tasks/cephfs/test_scrub_checks.py
- tasks/cephfs/test_strays.py
> [DNM]tasks/cephfs: cover snaps in test_strays

- tasks/cephfs/test_pool_perm.py
> tasks/cephfs: test for auth caps pool-setting restriction

- tasks/cephfs/test_journal_repair.py
This goes with ceph PR https://github.com/ceph/ceph/pull/6655
> tasks/cephfs: add TestJournalRepair.test_table_tool_take_inos

- suites/dummy/all/nop.yaml
This reverts commit a016f29e211e378a50fd833d940abbb49449c37b.
> Revert "dummy: only use the user playbook"

- suites/upgrade/infernalis/older/0-cluster/start.yaml
- suites/upgrade/infernalis/older/1-install/latest_infernalis_release.yaml
- suites/upgrade/infernalis/older/1-install/v9.1.0.yaml
- suites/upgrade/infernalis/older/2-workload/blogbench.yaml
- suites/upgrade/infernalis/older/2-workload/rbd.yaml
- suites/upgrade/infernalis/older/2-workload/testrados.yaml
- suites/upgrade/infernalis/older/3-upgrade-sequence/upgrade-mon-osd-mds.yaml
- suites/upgrade/infernalis/older/3-upgrade-sequence/upgrade-osd-mon-mds.yaml
- suites/upgrade/infernalis/older/4-final/monthrash.yaml
- suites/upgrade/infernalis/older/4-final/osdthrash.yaml
- suites/upgrade/infernalis/older/4-final/testrados.yaml
- suites/upgrade/infernalis/older/distros
@jdurgin pls review
Can be merged after https://github.com/ceph/teuthology/pull/714
> Initial draft for infernalis stable upgrade parallel tests

- tasks/buildpackages.py
- tasks/buildpackages/user-data.txt
> buildpackages: log the output of make

- tasks/buildpackages/centos-7.1-user-data.txt
- tasks/buildpackages/centos-7.2-user-data.txt
> buildpackages: support CentOS 7.1 and CentOS 7.2

- suites/rbd/singleton/all/rbd-vs-unmanaged-snaps.yaml
> suites/rbd: disable pool validation for pool snaps test

- suites/rados/singleton/all/radostool.yaml
The test sets and hits a quota; whitelist the message
> suites/rados/singleton/all/radostool: whitelist quota error

- tasks/ec_lost_unfound.py
Add test case for PR: https://github.com/ceph/ceph/pull/6298
Reviewed-by: Guang Yang <yguang@yahoo-inc.com>
> pg: add test cases for pg list_missing on EC pool

- suites/rados/basic/tasks/repair_test.yaml
- tasks/repair_test.py
This must be merged before we can merge ceph pull request 6669.
> repair_test: Add whitelist item for new stat error message

- suites/upgrade/hammer-x/f-h-x-offline/distros
- suites/upgrade/hammer-x/tiering/distros
- suites/upgrade/hammer-x/v0-94-4-stop/a-supported-distro.yaml
- suites/upgrade/hammer-x/v0-94-4-stop/distros
@liewegas @tmuthamizhan 
Pls review and merge
> Added ditros to f-h-x-offline, tiering, v0-94-4-stop tests

- suites/teuthology/no-ceph/distros/vps_centos7.1.yaml
- suites/teuthology/no-ceph/distros/vps_centos7.2.yaml
Signed-off-by: Zack Cerza <zack@redhat.com>
> suites/teuthology: Add CentOS 7.1 and 7.2

- distros/supported/centos_7.1.yaml
- distros/supported/centos_7.2.yaml
> Fixed symblink for os configs

- suites/fs/recovery/tasks/sessionmap.yaml
- tasks/ceph_manager.py
- tasks/cephfs/cephfs_test_case.py
- tasks/cephfs/fuse_mount.py
- tasks/cephfs/kernel_mount.py
- tasks/cephfs/mount.py
- tasks/cephfs/test_sessionmap.py
- tasks/cephfs/vstart_runner.py
This goes with ceph PR https://github.com/ceph/ceph/pull/6179
> tasks/cephfs: add TestSessionMap.test_session_reject

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
@tmuthamizhan 
@athanatos Pls merge
This fixes http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2016-01-18_10:02:02-upgrade:hammer-x-jewel-distro-basic-openstack/6241/
> Whitelisted 'wrongly marked me down'

- suites/fs/snaps/tasks/snaptests.yaml
- suites/kcephfs/cephfs/tasks/kclient_workunit_snaps.yaml
> suites/fs: enable all snapshost test scripts

- tasks/cephfs/test_sessionmap.py
To check that teardown is happening correctly when
sending commands to an MDS.
Fixes: #14048
> tasks: add TestSessionMap.test_[mount|tell]_conn_close

- suites/fs/basic/tasks/cephfs_journal_tool.yaml
> suites/fs: cephfs_journal_tool: wait for health after restart

- suites/rados/objectstore/fusestore.yaml
> rados/objecststore/fusestore.yaml: run ceph-objectstore-tool fuse test

- machine_types/schedule_rados_ovh.sh
> Made rados runs in ovh call vps.yaml

- config/rados.yaml
- suites/rados/basic/rados.yaml
- suites/rados/monthrash/rados.yaml
- suites/rados/multimon/rados.yaml
- suites/rados/objectstore/rados.yaml
- suites/rados/singleton-filestore/rados.yaml
- suites/rados/singleton-nomsgr/rados.yaml
- suites/rados/singleton/rados.yaml
- suites/rados/thrash-erasure-code-big/rados.yaml
- suites/rados/thrash-erasure-code-isa/rados.yaml
- suites/rados/thrash-erasure-code-shec/rados.yaml
- suites/rados/thrash-erasure-code/rados.yaml
- suites/rados/thrash/rados.yaml
- suites/rados/upgrade/rados.yaml
- suites/rados/verify/rados.yaml
> suites/rados: test random queue options

- suites/upgrade/hammer-x/tiering/0-cluster/start.yaml
> Whitelisted "wrongly marked me down" for the tiering tests

- suites/upgrade/hammer/newer/1-install/v0.94.3.yaml
@liewegas @tmuthamizhan Pls review and merge
> Added v0.94.3 to the mix

- suites/upgrade/infernalis/older/0-cluster/start.yaml
@jdurgin Pls review and merge
http://tracker.ceph.com/issues/14618
> Whitelisted "detected stalls on CPUs"

- suites/upgrade/hammer/newer/0-cluster/start.yaml
- suites/upgrade/hammer/older/0-cluster/start.yaml
> Whitelisted soft lockup, detected stalls on CPUs to avoid failures in ov

- distros/a-supported-distro.yaml
> Changed centos version to 7.2

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
- suites/upgrade/hammer-x/stress-split-erasure-code/3-thrash/default.yaml
- suites/upgrade/hammer-x/stress-split/3-thrash/default.yaml
- suites/upgrade/hammer-x/tiering/0-cluster/start.yaml
> Whitelisted 'soft lockup' and 'detected stalls on CPUs'

- tasks/cephfs/filesystem.py
- tasks/cephfs/test_data_scan.py
> tasks/cephfs: test sharded cephfs-data-scan

- suites/upgrade/hammer/newer/0-cluster/start.yaml
- suites/upgrade/hammer/newer/2-workload/rbd.yaml
- suites/upgrade/hammer/newer/2-workload/s3tests.yaml
- suites/upgrade/hammer/newer/3-upgrade-sequence/upgrade-mon-osd-mds.yaml
- suites/upgrade/hammer/newer/3-upgrade-sequence/upgrade-osd-mon-mds.yaml
- suites/upgrade/hammer/newer/4-final/testrgw.yaml
@jdurgin pls review and merge
seems working fine:
http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2016-02-18_06:05:30-upgrade:hammer-hammer-distro-basic-openstack/
http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2016-02-18_16:02:04-upgrade:hammer-hammer-distro-basic-openstack/
> Fixes #14652 (moved rbd and rgw tests on separate clients, forced s3tests branch)

- suites/fs/basic/tasks/cfuse_workunit_norstats.yaml
> add test for norstats functionality

- suites/upgrade/infernalis/older/0-cluster/start.yaml
- suites/upgrade/infernalis/older/2-workload/s3tests.yaml
- suites/upgrade/infernalis/older/4-final/testrgw.yaml
Moved rgw to a separate clients and added testrgw.yaml tests
@jdurgin pls review and merge 
tests passed http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2016-02-18_16:39:47-upgrade:infernalis-infernalis-distro-basic-openstack/
> Fixes #14808

- suites/krbd/unmap/tasks/unmap.yaml
@dillaman pls review and merge
> Fixes #14850

- suites/powercycle/osd/tasks/radosbench.yaml
> Reduced runtime for radosbench to 600

- suites/rados/basic/msgr/async.yaml
- suites/rados/basic/msgr/random.yaml
This reverts commit 0324772e23375b35c261a322fb82b2ff5a6b5db8.
> Revert "basic/msgr: remove async and random for now"

- suites/fs/verify/validater/valgrind.yaml
- suites/multimds/verify/validater/valgrind.yaml
- suites/rados/singleton-nomsgr/all/valgrind-leaks.yaml
- suites/rados/verify/validater/valgrind.yaml
- suites/rbd/valgrind/validator/helgrind.yaml
- suites/rbd/valgrind/validator/memcheck.yaml
- suites/rgw/verify/tasks/rgw_s3tests.yaml
- suites/rgw/verify/tasks/rgw_s3tests_multiregion.yaml
- suites/rgw/verify/tasks/rgw_swift.yaml
- suites/rgw/verify/validater/valgrind.yaml
This lets us get line numbers in the valgrind xml output.
> suites: debuginfo: true for valgrind

- suites/upgrade/hammer/newer/1-install/v0.94.6.yaml
Fixed #14905
@liewegas @mattbenjamin 
> Added v0.94.6 to stable upgrade suite

- suites/upgrade/infernalis/older/1-install/v9.2.1.yaml
- suites/upgrade/infernalis/point-to-point/point-to-point.yaml
Fixed #14904
@liewegas @tmuthamizhan 
> Adde v9.2.1 to stable upgrade suite

- suites/ceph-ansible/smoke/0-clusters/3-node.yaml
- suites/ceph-ansible/smoke/0-clusters/single_mon_osd.yaml
- suites/ceph-ansible/smoke/1-distros
- suites/ceph-ansible/smoke/2-setup/ceph_ansible.yaml
- suites/ceph-ansible/smoke/3-common/os_tuning/vm_friendly.yaml
- suites/ceph-ansible/smoke/3-common/source/upstream_stable.yaml
- suites/ceph-ansible/smoke/4-osd/devices/from_teuthology.yaml
- suites/ceph-ansible/smoke/4-osd/devices/osd_auto_discovery.yaml
- suites/ceph-ansible/smoke/4-osd/journal/collocated.yaml
- suites/ceph-ansible/smoke/5-tests/cls.yaml
- suites/ceph-ansible/smoke/5-tests/rbd_cli_tests.yaml
- suites/ceph-ansible/smoke/5-tests/rbd_import_export.yaml
Signed-off-by: Zack Cerza <zack@redhat.com>
> Add ceph-ansible suite

- suites/rbd/thrash/workloads/rbd_fsx_journal.yaml
- tasks/rbd_fsx.py
> rbd: add fsx journal replay test case

- suites/krbd/rbd/conf.yaml
- suites/krbd/singleton/conf.yaml
- suites/krbd/thrash/conf.yaml
- suites/krbd/unmap/conf.yaml
Jewel will update the default feature set to features
unsupported by krbd.
> krbd: override rbd defaults features to 1

- suites/ceph-ansible/smoke/2-setup/ceph_ansible.yaml
Uses the new feature:
https://github.com/ceph/ceph-ansible/pull/589
> ceph-ansible: Install ceph-test

- suites/rados/thrash/thrashers/pggrow.yaml
> rados: Enable odsync write for pggrow thrasher

- suites/upgrade/hammer-x/f-h-x-offline/4-after.yaml
Fixes #15012
@liewegas pls merge
Note to self: cherry-pick to infernalis 
> Removed branch: firefly from 4-after.yaml

- packages/packages.yaml
> packages: update for all the new debug packages we have in jewel

- tasks/rbd_fio.py
http://pulpito.ceph.redhat.com/vasu-2016-03-10_21:11:22-rbd-jewel---basic-magna/
Updating to 2.7 which is latest
> Update fio version to 2.7

- suites/rbd/singleton/all/admin_socket.yaml
- suites/rbd/singleton/all/mirror_image_replay.yaml
- suites/rbd/singleton/all/permissions.yaml
- suites/rbd/singleton/all/verify_pool.yaml
Signed-off-by: Josh Durgin <jdurgin@redhat.com>
> rbd: add some missing workunits

- suites/upgrade/client-upgrade/hammer-client-x/basic/2-workload/rbd_cli_import_export.yaml
- suites/upgrade/client-upgrade/hammer-client-x/rbd/0-cluster/start.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/basic/2-workload/rbd_cli_import_export.yaml
- suites/upgrade/client-upgrade/infernalis-client-x/rbd/0-cluster/start.yaml
> upgrade/client-upgrade: only use supported features for RBD tests

- tasks/cephfs/mount.py
- tasks/cephfs/test_strays.py
> tasks/cephfs: cover fancy layout in test_strays

- clusters/fixed-1.yaml
- suites/smoke/1node/tasks/ceph-deploy.yaml
- tasks/ceph_deploy.py
Fix issues listed here http://tracker.ceph.com/issues/14813
> fix ceph-deploy test

- suites/upgrade/infernalis-x/point-to-point-x/point-to-point.yaml
> upgrade/infernalis-x: do not to tier *Whiteout tests against post-infernalis cluster

- suites/rados/singleton-nomsgr/all/11429.yaml
- suites/rados/singleton-nomsgr/all/13234.yaml
> rados/singleton-nomsgr: run singleton upgrade tests on ubuntu

- suites/powercycle/osd/tasks/radosbench.yaml
> Changed run time for radosbench to 200

- suites/rbd/qemu/features/defaults.yaml
- suites/rbd/qemu/features/journaling.yaml
> suites/rbd: add qemu tests with journaling

- suites/rbd/maintenance/base/install.yaml
- suites/rbd/maintenance/clusters/fixed-3.yaml
- suites/rbd/maintenance/clusters/openstack.yaml
- suites/rbd/maintenance/qemu/xfstests.yaml
- suites/rbd/maintenance/workloads/dynamic_features.yaml
- suites/rbd/maintenance/workloads/rebuild_object_map.yaml
> suite/rbd: test dynamic features and rebuild object map

- suites/buildpackages/tests/tasks/release.yaml
- tasks/buildpackages.py
> buildpackages: provision a small build machine for tests

- tasks/ceph_deploy.py
> tasks: fix ceph_deploy call to Filesystem()

- suites/fs/basic/tasks/libcephfs_python.yaml
Depends on https://github.com/ceph/ceph/pull/7901
> suites: invoke libcephfs python tests

- tasks/cephfs/test_failover.py
...with cases for standby_for_rank and standby_for_fscid.
Fixes: #15065
> tasks/cephfs: extend TestMultiFilesystems

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
- suites/upgrade/hammer-x/parallel/2-workload/blogbench.yaml
- suites/upgrade/hammer-x/parallel/5-final-workload/blogbench.yaml
- suites/upgrade/infernalis-x/parallel/0-cluster/start.yaml
- suites/upgrade/infernalis-x/parallel/2-workload/blogbench.yaml
- suites/upgrade/infernalis-x/parallel/5-final-workload/blogbench.yaml
Fixes #15093
@jdurgin @gregsfortytwo FYI adding CepfFS workloads to -x jewel suites
> Added blogbench.yaml to parallel before and after -x upgrade steps

- tasks/cephfs/vstart_runner.py
> [DNM] tasks/cephfs: update vstart_runner for cmake build changes

- suites/rados/singleton-nomsgr/all/full-tiering.yaml
- suites/rados/singleton/all/thrash_cache_writeback_proxy_none.yaml
> rados/singleton: thrash proxy (not forward) cache mode

- suites/rados/singleton/all/thrash_cache_writeback_proxy_none.yaml
http://tracker.ceph.com/issues/15324 Fixes: #15324
> openstack: thrash_cache_writeback_proxy_none.yaml need bigger disks

- suites/powercycle/osd/tasks/radosbench.yaml
- suites/rados/thrash-erasure-code/workloads/ec-radosbench.yaml
- suites/rados/thrash/workloads/admin_socket_objecter_requests.yaml
- suites/rados/thrash/workloads/radosbench.yaml
- suites/rados/upgrade/hammer-x-singleton/7-workload/radosbench.yaml
- suites/smoke/basic/tasks/rados_bench.yaml
- suites/upgrade/firefly-hammer-x/stress-split/07-workload/radosbench.yaml
- suites/upgrade/firefly-hammer-x/stress-split/19-workload/radosbench.yaml
- suites/upgrade/hammer-x/stress-split/7-workload/radosbench.yaml
- suites/upgrade/infernalis-x/stress-split/7-workload/radosbench.yaml
I hit an ENOSPC after 150s on bluestore.
> suites: radosbench 180 -> 150s

- tasks/buildpackages/debian-8.0-user-data.txt
> buildpackages: add debian 8.0 support

- suites/samba/mount/kclient.yaml
Fixes: http://tracker.ceph.com/issues/15304
> samba: run kclient mount tests on testing kernel

- distros/all/ubuntu_16.04.yaml
> distros: add ubuntu 16.04 / xenial

- suites/rados/singleton/all/admin-socket.yaml
> admin malloc interface tests

- tasks/radosgw_admin.py
- tasks/util/rgw.py
> rgw: policy acl format should be xml

- tasks/buildpackages/ubuntu-16.04-user-data.txt
> buildpackages: xenial support

- tasks/buildpackages/ubuntu-16.04-user-data.txt
> buildpackages: add ubuntu 16.04 xenial support

- suites/teuthology/rgw/tasks/s3tests-civetweb.yaml
@oritwas @zmc Pls review and merge
> Added civetweb test case

- suites/rgw/singleton/fs/xfs.yaml
> rgw: move xfs to a seperate directory

- suites/ceph-ansible/smoke/5-tests/ceph-admin-commands.yaml
- suites/ceph-deploy/basic/tasks/ceph-admin-commands.yaml
Renaming the yaml and workunits for better clarity
> Signed-off-by: Tamil Muthamizhan <tmuthami@redhat.com>

- suites/rados/objectstore/keyvaluedb.yaml
> rados/objectstore: add ceph_test_keyvaluedb test

- suites/rgw/multifs/overrides.yaml
- suites/rgw/multifs/tasks/rgw_s3tests.yaml
- suites/rgw/singleton/all/radosgw-admin-data-sync.yaml
- suites/rgw/singleton/all/radosgw-admin-multi-region.yaml
- suites/rgw/singleton/all/radosgw-convert-to-region.yaml
- suites/rgw/singleton/fs/xfs.yaml
- suites/rgw/singleton/overrides.yaml
- suites/rgw/verify/overrides.yaml
- suites/rgw/verify/tasks/rgw_s3tests.yaml
- suites/rgw/verify/tasks/rgw_s3tests_multiregion.yaml
- tasks/radosgw_admin.py
- tasks/rgw.py
- tasks/util/rgw.py
Changes needed for support new multisite implementation.
> Wip rgw new multisite

- suites/rados/singleton/all/resolve_stuck_peering.yaml
- tasks/resolve_stuck_peering.py
Signed-off-by: shylesh kumar <shylesh.mohan@gmail.com>
> Rados: Tracker-13531-resolve stuck peering

- tasks/ceph_manager.py
- tasks/thrashosds.py
Add dump_ops_enable which continuously dumps ops using 3 commands
Add optrack_toggle_delay to alternate op tracking enablement
> Add dump_ops_enable and optrack_toggle_delay options

- tasks/ceph_manager.py
- tasks/repair_test.py
- tasks/scrub_test.py
- tasks/thrashosds.py
This is on top of another pull request wip-8885. I want to see what happens after that one merges.
> Changes for wip-13507 and test fixes

- suites/powercycle/osd/tasks/rados_api_tests.yaml
- suites/rados/basic/tasks/rados_api_tests.yaml
- suites/rados/monthrash/workloads/rados_api_tests.yaml
- suites/rados/thrash/workloads/rados_api_tests.yaml
- suites/rados/verify/tasks/rados_api_tests.yaml
- suites/smoke/basic/tasks/rados_api_tests.yaml
> drop broken name length config args

- suites/rados/singleton/all/resolve_stuck_peering.yaml
- tasks/resolve_stuck_peering.py
Reverts ceph/ceph-qa-suite#981
It actually works as is.
> Revert "Revert "Rados: Tracker-13531-resolve stuck peering""

- tasks/ceph.py
- tasks/ceph_objectstore_tool.py
- tasks/cephfs/kernel_mount.py
- tasks/filestore_idempotent.py
- tasks/resolve_stuck_peering.py
Fixes the multi-cluster related failures from yuriw-2016-05-10_10:56:12-rados-wip-yuri-testing-distro-basic-smithi/, plus a cephfs test
> fixes for some issues caused by the multi-cluster branch

- suites/upgrade/jewel-x/point-to-point-x/distros
- suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
Initial check in for point-to-point-x for 10.2.x (jewel) releases suite.
Fixes http://tracker.ceph.com/issues/14339
> Added v10.2.0 => jewel upgrade case

- nightlies/cron_wrapper
> Added echo to log a command name to the log file

- tasks/cephfs/mount.py
- tasks/cephfs/test_volume_client.py
Fixes: http://tracker.ceph.com/issues/15599
> tasks/cephfs: test 'df' output in volumeclient

- suites/rbd/mirror/workloads/rbd-mirror-stress-workunit.yaml
> suites/rbd: added replication stress test workunit

- tasks/cephfs/test_volume_client.py
Test whether mount access to volumes can be restricted to read-only.
Fixes: http://tracker.ceph.com/issues/15614
Signed-off-by: Ramana Raja <rraja@redhat.com>
> tasks/cephfs: test read-only authorization for volumes

- tasks/cephfs/test_sessionmap.py
Passing here: http://qa-proxy.ceph.com/teuthology/jspray-2016-05-23_11:57:19-fs:recovery-master---basic-mira/209404/teuthology.log
Fixes: http://tracker.ceph.com/issues/15900
> tasks/cephfs: fix failure in test_mount_conn_close

- tasks/buildpackages.py
http://travaux.ovh.net/?do=details&id=17532
> openstack: ovh renamed flavors : s/eg/hg/

- suites/rbd/mirror/workloads/rbd-mirror-stress-workunit.yaml
(cherry picked from commit ecbda33b52c1a139cdf31562ac81a433b7e1dc68)
> jewel: suites/rbd: added replication stress test workunit

- suites/rbd/basic/clusters/openstack.yaml
- suites/rbd/cli/clusters
- suites/rbd/cli/clusters/fixed-1.yaml
- suites/rbd/librbd/clusters/openstack.yaml
- suites/rbd/mirror/cluster/openstack.yaml
- suites/rbd/singleton/openstack.yaml
- suites/rbd/valgrind/clusters
- suites/rbd/valgrind/clusters/fixed-1.yaml
> rbd: provision volumes to format as XFS

- suites/fs/recovery/clusters/4-remote-clients.yaml
- suites/fs/recovery/mounts/ceph-fuse.yaml
- tasks/cephfs/mount.py
- tasks/cephfs/test_volume_client.py
- tasks/cephfs/vstart_runner.py
The test side of https://github.com/ceph/ceph/pull/9430
Tested here: http://pulpito.ceph.com/jspray-2016-06-02_15:43:38-fs-wip-manila-backports---basic-mira/
> jewel: backports needed for Manila

- suites/rados/singleton-nomsgr/all/16113.yaml
> suites/rados: add test for 16113

- suites/fs/permission/mount/ceph-fuse.yaml
> suites/fs: fix config for enabling libcephfs posix ACL

- tasks/object_source_down.py
- tasks/osd_backfill.py
- tasks/osd_recovery.py
- tasks/peer.py
- tasks/recovery_bench.py
- tasks/rep_lost_unfound_delete.py
- tasks/scrub.py
> [jewel]: tasks: fix non-existent sleep function

- suites/fs/permission/tasks/cfuse_workunit_misc.yaml
> suites/fs/permission: run qa/workunits/fs/misc/{acl.sh,chmod.sh}

- tasks/cephfs/test_failover.py
Even though check_subs was broken, the multiclient
test was still passing because it didn't test that
clients survived a failover in the multi-filesystem
case.
Fixes: http://tracker.ceph.com/issues/16022
> tasks/cephfs: reproducer for #16022

- tasks/cephfs/test_failover.py
> tasks/cephfs: update tests for mount-by-fs-name

- suites/fs/recovery/tasks/client-readahad.yaml
- tasks/cephfs/test_readahead.py
Test case for: https://github.com/ceph/ceph/pull/9374
Issue: http://tracker.ceph.com/issues/16024
Signed-off-by: Patrick Donnelly <batrick@batbytes.com>
> cephfs: test readahead is working

- tasks/mds_thrash.py
> reference the kill_mds_by_rank function in the right location

- suites/fs/recovery/tasks/sessionmap.yaml
- suites/fs/recovery/tasks/volume-client.yaml
Two tests are sensitive to the switch to async msgr
http://tracker.ceph.com/issues/16288
http://tracker.ceph.com/issues/16276
> suites/fs: use simple messenger some places

- suites/rados/singleton-nomsgr/all/11429.yaml
- suites/rados/singleton-nomsgr/all/lfn-upgrade-hammer.yaml
- suites/rados/singleton-nomsgr/all/lfn-upgrade-infernalis.yaml
- suites/rados/singleton/all/pg-removal-interruption.yaml
Fixes http://tracker.ceph.com/issues/16334
Fixes http://tracker.ceph.com/issues/16332
> 16334 and 16332 fixes

- suites/rbd/thrash/workloads/rbd_fsx_nbd.yaml
- tasks/rbd_fsx.py
> rbd: added rbd-nbd fsx test case

- suites/rbd/thrash/workloads/rbd_fsx_nbd.yaml
- tasks/rbd_fsx.py
(cherry picked from commit 7425e2d7a64e2962f6a7bc6f6ba09ee9137e7a14)
> jewel: rbd: added rbd-nbd fsx test case

- tasks/scrub_test.py
> tasks/scrub_test: use fuse path (do not assume filestore!)

- tasks/scrub_test.py
Enhance get_pgid() to return passed value if it is already a pgid
Signed-off-by: David Zafman <dzafman@redhat.com>
> test: Eliminate racey scrubbing in scrub_test.py

- tasks/resolve_stuck_peering.py
> resolve_stuck_peering: reset stats while looping

- tasks/osd_recovery.py
> osd_recovery: add delay to ensure maps propogate

- tasks/s3roundtrip.py
Fixes tracker bug 15453
Signed-off-by: Warren Usui <wusui@redhat.com>
> Allow force-branch for s3roundtrip tests.

- suites/rbd/singleton/all/formatted-output.yaml
Fixes http://tracker.ceph.com/issues/16551
> rbd: pull formatted-output.t from the relevant branch

- suites/smoke/systemd/distro/centos_7.2.yaml
- suites/smoke/systemd/distro/ubuntu_14.04.yaml
- suites/smoke/systemd/distro/ubuntu_16.04.yaml
- suites/smoke/systemd/tasks/systemd.yaml
- tasks/systemd.py
@branto1 @ktdreyer  Tests for systemd on both ubuntu and centos, 
Right now its failing which i believe is due to systemd issue,  will be testing on some more branches
http://pulpito.ceph.com/vasu-2016-05-19_09:44:01-smoke:systemd-jewel---basic-mira/202058/
> Wip systemd tests

- tasks/cephfs/cephfs_test_case.py
- tasks/cephfs/test_cap_flush.py
- tasks/cephfs/test_damage.py
- tasks/cephfs/test_data_scan.py
- tasks/cephfs/test_journal_repair.py
- tasks/cephfs/test_pool_perm.py
- tasks/cephfs/test_strays.py
- tasks/cephfs/vstart_runner.py
Mixture of things that tripped up while running tests all together on a vstart cluster
> tasks/cephfs: vstart_runner fixes

- suites/rbd/singleton/all/mirror_image_replay.yaml
Fixes: http://tracker.ceph.com/issues/16539
Signed-off-by: Mykola Golub <mgolub@mirantis.com>
> rbd-mirror: remove ceph_test_rbd_mirror_image_replay test case

- suites/upgrade/hammer-x/point-to-point-x/0-tz-eastern.yaml
Fixes: http://tracker.ceph.com/issues/16306
> upgrade/hammer-x/point-to-point-x: remove 0-tz-eastern.yaml

- suites/fs/thrash/tasks/cfuse_workunit_snaptests.yaml
> fs: add snapshot tests to mds thrashing

- tasks/cephfs/test_volume_client.py
tasks/cephfs/test_volume_client: test authentication metadata
Test the use cases for the authentication metadata stored
by the volume client:
* Obtain the list of auth IDs having access to a volume.
* Restrict volume access to auth IDs of a single (OpenStack)
tenant to enforce strong tenant isolation of volumes.
> tasks/cephfs/test_volume_client: test authentication metadata

- machine_types/schedule_rados.sh
- machine_types/schedule_rados_ovh.sh
> Added option to search for newest good/built commit (7 commits back)

- tasks/ceph_manager.py
Fixes: http://tracker.ceph.com/issues/15655
> ceph_manager: test [test-]reweight-by-(utilization|pg)

- machine_types/schedule_rados.sh
- machine_types/schedule_rados_ovh.sh
> Reduce number of jobs for hammer branch

- tasks/cephfs/test_volume_client.py
tasks/cephfs: test read-only authorization for volumes
```
Test whether mount access to volumes can be restricted to read-only.
Fixes: http://tracker.ceph.com/issues/15999
```
tasks/cephfs/test_volume_client: test authentication metadata
````
Test the usecases for the authentication metadata stored
by the volume client:
* Obtain the list of auth IDs having access to a volume.
* Restrict volume access to auth IDs of a single (OpenStack)
tenant to enforce strong tenant isolation of volumes.
Fixes: http://tracker.ceph.com/issues/16831
Fixes:  http:// tracker.ceph.com/issues/16830
````
> jewel: backports for OpenStack Manila

- suites/fs/recovery/tasks/forward-scrub.yaml
Fixes: http://tracker.ceph.com/issues/16879
> suites/fs: fix log whitelist for inotable repair

- packages/packages.yaml
Signed-off-by: Ricardo Dias <rdias@suse.com>
(cherry picked from commit 0216330568fc1dec2e866bbfd1e49dc42266e1ab)
> packages.yaml: reflect python-ceph package split

- nightlies/cron_wrapper
> Added stderr to the log file in addition to stdout

- tasks/radosgw_admin.py
Fixes: http://tracker.ceph.com/issues/17025
> rgw: data_extra_pool is unique per zone

- suites/upgrade/jewel-x/parallel/5-final-workload/rados_mon_thrash.yaml
- suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
Needs https://github.com/ceph/ceph/pull/10716
> jewel-x: use jewel-compatible librados tests for upgraded clients

- tasks/ceph_manager.py
- tasks/mds_thrash.py
- tasks/thrashosds.py
http://tracker.ceph.com/issues/17124
> Fix console handling in tasks

- tasks/ceph_deploy.py
@alfredodeza need this on hammer to test with hammer builds
> hammer packport for dev-commit option

- tasks/ceph_deploy.py
> jewel backport for --dev-commit option

- suites/rados/multimon/clusters/21.yaml
- suites/rados/multimon/clusters/3.yaml
- suites/rados/multimon/clusters/6.yaml
- suites/rados/multimon/clusters/9.yaml
- suites/rados/objectstore/ceph_objectstore_tool.yaml
- suites/rados/objectstore/filejournal.yaml
- suites/rados/objectstore/filestore-idempotent-aio-journal.yaml
- suites/rados/objectstore/filestore-idempotent.yaml
- suites/rados/objectstore/objectcacher-stress.yaml
- suites/rados/objectstore/objectstore.yaml
Ref: http://tracker.ceph.com/issues/17152
> openstack: add disks where necessary

- tasks/cephfs/test_failover.py
Fixes: http://tracker.ceph.com/issues/16909
> tasks/cephfs: test standby replay teardown on rank stop

- suites/rbd/singleton/all/mirror_image_replay.yaml
http://tracker.ceph.com/issues/17066
> jewel: rbd-mirror: remove ceph_test_rbd_mirror_image_replay test case

- suites/krbd/rbd-nomount/conf.yaml
- suites/krbd/rbd/conf.yaml
- suites/krbd/rbd/tasks/rbd_fio.yaml
- suites/krbd/singleton/conf.yaml
- suites/krbd/thrash/conf.yaml
- suites/krbd/thrash/workloads/rbd_fio.yaml
- suites/krbd/unmap/conf.yaml
> krbd: enable exclusive-lock feature

- suites/krbd/unmap/ceph/ceph.yaml
- suites/krbd/unmap/clusters/fixed-1.yaml
- suites/krbd/unmap/clusters/separate-client.yaml
- suites/krbd/unmap/kernels/pre-single-major.yaml
http://tracker.ceph.com/issues/17222
> Backport krbd/unmap fixes

- suites/upgrade/client-upgrade/hammer-client-x/basic/2-workload/rbd_api_tests.yaml
Fixes: http://tracker.ceph.com/issues/16717
Signed-off-by: Mykola Golub <mgolub@mirantis.com>
> suites/upgrade: override rbd_default_features config back to pre-Jewel

- suites/smoke/basic/tasks/rbd_workunit_suites_iozone.yaml
> smoke: mask out unsupported image features for krbd iozone test

- suites/smoke/basic/tasks/rbd_workunit_suites_iozone.yaml
(cherry picked from commit 77949e5cfc1231c96417e90aadc1573137c4b4d7)
> jewel: smoke: mask out unsupported image features for krbd iozone test

- suites/fs/basic/tasks/libcephfs_java.yaml
> suites/fs: pin java test to ubuntu

- suites/fs/permission/dirfrag/frag_enable.yaml
- tasks/ceph.py
Otherwise places we set mds_bal_frag have
no effect.
> tasks/ceph: enable dirfrags in cephfs

- tasks/ceph_manager.py
Reverts ceph/ceph-qa-suite#1128
> Revert "ceph_manager: lower mon_reweight_min_bytes_per_osd to 10"

- tasks/cephfs/vstart_runner.py
So that for folks with sources in typical locations
(or typical on my workstation at least!) invoking
vstart_runner is less of a mouthful.
> tasks/cephfs: add default paths to vstart_runner

- suites/rgw/multifs/tasks/rgw_s3tests.yaml
- suites/rgw/verify/tasks/rgw_s3tests.yaml
- suites/rgw/verify/tasks/rgw_s3tests_multiregion.yaml
- suites/smoke/basic/tasks/rgw_ec_s3tests.yaml
- suites/smoke/basic/tasks/rgw_s3tests.yaml
- suites/teuthology/rgw/tasks/s3tests-civetweb.yaml
- suites/teuthology/rgw/tasks/s3tests-fastcgi.yaml
- suites/teuthology/rgw/tasks/s3tests-fcgi.yaml
- suites/upgrade/firefly-hammer-x/parallel/7-final-workload/rgw_s3tests.yaml
Signed-off-by: Daniel Gryniewicz <dang@redhat.com>
Requires same PR for s3-tests
> rgw - Add config for testing lifecycle expiration

- tasks/ceph_manager.py
When killing an osd, split all pools with a low threshold.
This will slow down tests, but should not impact correctness.
Signed-off-by: Josh Durgin <jdurgin@redhat.com>
(cherry picked from commit f28f881bda0ad426bfa9c0e22cc4658b2ce2ec5d)
> ceph_manager: test offline split via ceph-objectstore-tool

- suites/fs/basic/tasks/cephfs_scrub_tests.yaml
- suites/fs/recovery/tasks/damage.yaml
- suites/fs/recovery/tasks/forward-scrub.yaml
Fixes: http://tracker.ceph.com/issues/16016
> suites: update log whitelist for scrub msg

- suites/rbd/mirror/workloads/rbd-mirror-stress-workunit.yaml
> suites/rbd: increase timeout for rbd-mirror stress test

- suites/rados/upgrade/jewel-x-singleton/0-cluster/openstack.yaml
- suites/rados/upgrade/jewel-x-singleton/0-cluster/start.yaml
- suites/rados/upgrade/jewel-x-singleton/1-jewel-install/jewel.yaml
- suites/rados/upgrade/jewel-x-singleton/2-partial-upgrade/firsthalf.yaml
- suites/rados/upgrade/jewel-x-singleton/3-thrash/default.yaml
- suites/rados/upgrade/jewel-x-singleton/4-mon/mona.yaml
- suites/rados/upgrade/jewel-x-singleton/5-workload/rbd-cls.yaml
- suites/rados/upgrade/jewel-x-singleton/5-workload/rbd-import-export.yaml
- suites/rados/upgrade/jewel-x-singleton/5-workload/readwrite.yaml
- suites/rados/upgrade/jewel-x-singleton/5-workload/snaps-few-objects.yaml
- suites/rados/upgrade/jewel-x-singleton/6-next-mon/monb.yaml
- suites/rados/upgrade/jewel-x-singleton/7-workload/radosbench.yaml
- suites/rados/upgrade/jewel-x-singleton/7-workload/rbd_api.yaml
- suites/rados/upgrade/jewel-x-singleton/8-next-mon/monc.yaml
- suites/rados/upgrade/jewel-x-singleton/9-workload/rbd-python.yaml
- suites/rados/upgrade/jewel-x-singleton/9-workload/rgw-swift.yaml
- suites/rados/upgrade/jewel-x-singleton/9-workload/snaps-many-objects.yaml
- suites/rados/upgrade/rados.yaml
> Added jewel-x-singleton

- tasks/cephfs/test_volume_client.py
... in ceph_volume_client.
Signed-off-by: Ramana Raja <rraja@redhat.com>
> [DNM] tasks/cephfs : test recovery of partial auth update

- tasks/cephfs/filesystem.py
- tasks/cephfs/test_data_scan.py
Fixes: http://tracker.ceph.com/issues/17249
> tasks/cephfs: add TestDataScan.test_pg_files

- suites/fs/recovery/tasks/forward-scrub.yaml
- tasks/cephfs/filesystem.py
- tasks/cephfs/test_forward_scrub.py
Fixes: http://tracker.ceph.com/issues/17639
> tasks/cephfs: add TestForwardScrub.test_backtrace_repair

- tasks/cephfs/cephfs_test_case.py
- tasks/cephfs/test_mantle.py
Tests load/execute balancers but doesn't test balancing behavior; should be ok as long as Mantle is only used by expert experimenters.
Signed-off-by: Michael Sevilla <mikesevilla3@gmail.com>
> mds: add tests for mantle (programmable balancer)

- tasks/cephfs/mount.py
- tasks/cephfs/test_data_scan.py
> tasks/cephfs: add TestDataScan.test_scan_links

- packages/packages.yaml
- suites/mgr/basic/clusters/2-node-mgr.yaml
- suites/mgr/basic/debug/mgr.yaml
- suites/mgr/basic/fs/xfs.yaml
- suites/mgr/basic/tasks/failover.yaml
- tasks/ceph.py
- tasks/ceph_manager.py
- tasks/ceph_test_case.py
- tasks/cephfs/cephfs_test_case.py
- tasks/cephfs/filesystem.py
- tasks/cephfs_test_runner.py
- tasks/mgr/mgr_test_case.py
- tasks/mgr/test_failover.py
- tasks/systemd.py
- tasks/vstart_runner.py
This is an adaptation of the classes used for cephfs functional tests, to use them for ceph-mgr (https://github.com/ceph/ceph/pull/10328)
The body of REST API tests from the calamari tree will get ported into this framework.
> Create ceph-mgr tests

- tasks/ceph_manager.py
- tasks/divergent_priors.py
- tasks/divergent_priors2.py
- tasks/reg11184.py
> tasks: use new generic objectstore_blackhole option

- suites/rados/singleton-nomsgr/all/11429.yaml
- suites/rados/singleton-nomsgr/all/16113.yaml
- suites/upgrade/hammer-x/f-h-x-offline/2-upgrade.yaml
- suites/upgrade/hammer-x/f-h-x-offline/3-infernalis.yaml
- suites/upgrade/hammer-x/f-h-x-offline/3-jewel.yaml
- suites/upgrade/hammer-x/parallel/3-upgrade-sequence/upgrade-all.yaml
- suites/upgrade/hammer-x/parallel/3-upgrade-sequence/upgrade-mon-osd-mds.yaml
- suites/upgrade/hammer-x/parallel/4-infernalis.yaml
- suites/upgrade/hammer-x/parallel/4-jewel.yaml
- suites/upgrade/hammer-x/v0-94-4-stop/v0-94-4-stop.yaml
> releases/jewel: set require_jewel_osds

- suites/rgw/system/tasks/Mbuckets_with_Nobjects.yaml
- suites/rgw/system/tasks/acls.yaml
- suites/rgw/system/tasks/acls_all_usrs.yaml
- suites/rgw/system/tasks/acls_copy_obj.yaml
- suites/rgw/system/tasks/acls_reset.yaml
- suites/rgw/system/tasks/basic_versioning.yaml
- suites/rgw/system/tasks/bucket_with_delete.yaml
- suites/rgw/system/tasks/delete_key_versions.yaml
- suites/rgw/system/tasks/multipart_upload.yaml
- suites/rgw/system/tasks/multipart_upload_cancel.yaml
- suites/rgw/system/tasks/multipart_upload_download.yaml
- suites/rgw/system/tasks/suspend_versioning.yaml
- suites/rgw/system/tasks/version_with_revert.yaml
Adding RGW System test case yamls in suits
> added rgw_system_test_yaml

- suites/rgw/system/tasks/Mbuckets_with_Nobjects.yaml
- suites/rgw/system/tasks/bucket_with_delete.yaml
- tasks/rgw_system_test.py
corrected the yaml file for 2 tests and doc string rgw_system_case task
> corrected the yaml and doctring

- suites/hadoop/basic/clusters/fixed-3.yaml
Workaround for http://tracker.ceph.com/issues/16640
Signed-off-by: John Spray john.spray@redhat.com
> suites/hadoop: run only on ubuntu

- suites/rgw/system/tasks/bucket_with_delete.yaml
the missing task name was causing error in the yaml. added the task in the yaml
> added the task name in the yaml

- suites/upgrade/hammer-x/parallel/3-upgrade-sequence/upgrade-all.yaml
- suites/upgrade/hammer-x/parallel/3-upgrade-sequence/upgrade-mon-osd-mds.yaml
- suites/upgrade/hammer-x/v0-94-4-stop/v0-94-4-stop.yaml
Fixes: http://tracker.ceph.com/issues/17808
> upgrade/hammer-x: wait for osdmaps to propagate

- distros/supported/ubuntu_16.04.yaml
> distros/supported: add xenial

- suites/upgrade/infernalis-x/stress-split-erasure-code-x86_64/3-thrash/default.yaml
- suites/upgrade/infernalis-x/stress-split-erasure-code/3-thrash/default.yaml
- suites/upgrade/infernalis-x/stress-split/3-thrash/default.yaml
Fixes: http://tracker.ceph.com/issues/17683
> upgrade: disable ceph-objectstore-tool test in infernalis-x

- suites/rados/upgrade/jewel-x-singleton/1-jewel-install/jewel.yaml
> rados/upgrade: skip libcephfs-devel install

- suites/rados/singleton-nomsgr/all/cache-fs-trunc.yaml
> rados/singleton-nomsgr/all/cache-fs-trunc: debug

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
- suites/upgrade/hammer-x/stress-split/3-thrash/default.yaml
- suites/upgrade/hammer-x/tiering/0-cluster/start.yaml
Signed-off-by: Tamil Muthamizhan <tmuthami@redhat.com>
> DO NOT whitelist CRC mismatch

- suites/upgrade/jewel-x/point-to-point-x/distros
- suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
> Added /upgrade/jewel-x/point-to-point-x

- suites/upgrade/jewel-x/parallel/1-jewel-install/jewel.yaml
- suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
- suites/upgrade/jewel-x/stress-split/1-jewel-install/jewel.yaml
Fixes http://tracker.ceph.com/issues/17902
> Added excluded packages "'libcephfs-devel','libcephfs-dev'"

- tasks/cephfs/filesystem.py
Credit to John Spray for identifying the problem/cause.
Fixes: http://tracker.ceph.com/issues/17894
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>
> cephfs: get new fsmap after marking clusters down

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
> upgrade/hammer-x: debug client

- suites/upgrade/hammer-x/parallel/0-cluster/start.yaml
- suites/upgrade/hammer-x/stress-split/2-partial-upgrade/firsthalf.yaml
- suites/upgrade/hammer-x/stress-split/3-thrash/default.yaml
- suites/upgrade/hammer-x/stress-split/8-finish-upgrade/last-osds-and-monc.yaml
- suites/upgrade/hammer-x/tiering/0-cluster/start.yaml
whitelisted CRC mismatch and added upgrade for second
half of the cluster
Signed-off-by: Tamil Muthamizhan <tmuthami@redhat.com>
> whitelist CRC mismatch

- suites/upgrade/jewel-x/point-to-point-x/distros
- suites/upgrade/jewel-x/point-to-point-x/distros/centos_7.2.yaml
- suites/upgrade/jewel-x/point-to-point-x/distros/ubuntu_14.04.yaml
- suites/upgrade/jewel-x/point-to-point-x/point-to-point-upgrade.yaml
Fixes http://tracker.ceph.com/issues/17960
Signed-off-by: Yuri Weinstein yweinste@redhat.com
> Removed xenial + Excluded librgw2

- suites/rados/singleton-nomsgr/all/11429.yaml
- suites/rados/singleton-nomsgr/all/13234.yaml
- suites/rados/singleton-nomsgr/all/16113.yaml
- suites/rados/singleton-nomsgr/all/lfn-upgrade-hammer.yaml
- suites/rados/singleton-nomsgr/all/lfn-upgrade-infernalis.yaml
> suites/rados: s/trusty/"14.04"/

- suites/rbd/cli/pool/ec-data-pool.yaml
- suites/rbd/librbd/pool/ec-data-pool.yaml
- suites/rbd/qemu/pool/ec-data-pool.yaml
> ec-data-pool: enable the hacky_overwrites flag

- suites/rados/basic/tasks/rados_striper.yaml
Signed-off-by: Sebastien Ponce sebastien.ponce@cern.ch
> rados: Added tests for the striper layer of rados

- tasks/aver.py
This closes http://tracker.ceph.com/issues/12378
> Adds task to wrap the aver utility

- suites/fs/recovery/tasks/fragment.yaml
- tasks/ceph_test_case.py
- tasks/cephfs/cephfs_test_case.py
- tasks/cephfs/filesystem.py
- tasks/cephfs/test_fragment.py
- tasks/vstart_runner.py
This goes with https://github.com/ceph/ceph/pull/12022
> Directory fragmentation tests

- suites/fs/multiclient/tasks/fsx-mpi.yaml.disabled
I couldn't merge this myself due to master being protected.
https://github.com/ceph/ceph-qa-suite/pull/284
> Fixes for PR284

- suites/rgw/system/tasks/Mbuckets_with_Nobjects_shards.yaml
- tasks/rgw_system_test.py
added new Yaml for Sharding and bucket object quota limit.
> added new yaml for sharding and bucket object quota limit

- suites/upgrade/hammer-jewel-x/parallel/0-cluster/start.yaml
This is from teh librados api test.
> upgrade/hammer-jewel-x: whitelist quota

- suites/krbd/unmap/tasks/unmap.yaml
- suites/rbd/singleton/all/formatted-output.yaml
- tasks/cram.py
Signed-off-by: Venky Shankar <vshankar@redhat.com>
> cram: support fetching from sha1 branch, tag, commit hash

- tasks/ceph_manager.py
- tasks/thrashosds.py
Backport testing of only dump ops fix
> hammer: SIGABRT in TrackedOp::dump() via dump_ops_in_flight()

- suites/rgw/system/tasks/Mbuckets_with_Nobjects_shards.yaml
- tasks/rgw_system_test.py
correct the typo in suites/rgw/system/tasks/Mbuckets_with_Nobjects_shards.yaml and added missing config  for test_acls_reset
> typo correction and missing config added
